// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDealer = "dealers"

// Dealer mapped from table <dealers>
type Dealer struct {
	ID            string     `gorm:"column:id;primaryKey" json:"id"`
	Name          string     `gorm:"column:name;not null" json:"name"`
	ContactPerson *string    `gorm:"column:contact_person" json:"contact_person"`
	Phone         *string    `gorm:"column:phone" json:"phone"`
	Email         *string    `gorm:"column:email" json:"email"`
	Province      *string    `gorm:"column:province" json:"province"`
	City          *string    `gorm:"column:city" json:"city"`
	District      *string    `gorm:"column:district" json:"district"`
	Address       *string    `gorm:"column:address" json:"address"`
	ParentID      *string    `gorm:"column:parent_id" json:"parent_id"`
	TenantID      string     `gorm:"column:tenant_id;not null" json:"tenant_id"`
	CreatedAt     *time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt     *time.Time `gorm:"column:updated_at" json:"updated_at"`
	Remark        *string    `gorm:"column:remark" json:"remark"`
}

// TableName Dealer's table name
func (*Dealer) TableName() string {
	return TableNameDealer
}
