// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDeviceUserBinding = "device_user_bindings"

// DeviceUserBinding mapped from table <device_user_bindings>
type DeviceUserBinding struct {
	ID          string     `gorm:"column:id;primaryKey" json:"id"`
	UserID      string     `gorm:"column:user_id;not null" json:"user_id"`
	DeviceID    string     `gorm:"column:device_id;not null" json:"device_id"`
	BindingTime *time.Time `gorm:"column:binding_time" json:"binding_time"`
	IsOwner     *bool      `gorm:"column:is_owner;default:false" json:"is_owner"`
	Remark      *string    `gorm:"column:remark" json:"remark"`
}

// TableName DeviceUserBinding's table name
func (*DeviceUserBinding) TableName() string {
	return TableNameDeviceUserBinding
}
