// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDeviceBattery = "device_batteries"

// DeviceBattery mapped from table <device_batteries>
type DeviceBattery struct {
	DeviceID          string     `gorm:"column:device_id;primaryKey" json:"device_id"`
	BatteryModelID    *string    `gorm:"column:battery_model_id" json:"battery_model_id"`
	DealerID          *string    `gorm:"column:dealer_id" json:"dealer_id"`
	ProductionDate    *time.Time `gorm:"column:production_date" json:"production_date"`
	WarrantyExpireDate *time.Time `gorm:"column:warranty_expire_date" json:"warranty_expire_date"`
	ActivationDate    *time.Time `gorm:"column:activation_date" json:"activation_date"`
	ActivationStatus  *string    `gorm:"column:activation_status;default:INACTIVE" json:"activation_status"`
	TransferStatus    *string    `gorm:"column:transfer_status;default:FACTORY" json:"transfer_status"`
	BatchNumber       *string    `gorm:"column:batch_number" json:"batch_number"`
	SOC               *float64   `gorm:"column:soc" json:"soc"`
	SOH               *float64   `gorm:"column:soh" json:"soh"`
	UpdatedAt         *time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName DeviceBattery's table name
func (*DeviceBattery) TableName() string {
	return TableNameDeviceBattery
}
