// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDeviceOrgTransfer = "device_org_transfers"

// DeviceOrgTransfer mapped from table <device_org_transfers>
// 设备组织转移记录表
type DeviceOrgTransfer struct {
	ID           string     `gorm:"column:id;primaryKey;comment:记录ID" json:"id"`                          // 记录ID
	DeviceID     string     `gorm:"column:device_id;not null;comment:设备ID" json:"device_id"`              // 设备ID
	FromOrgID    *string    `gorm:"column:from_org_id;comment:转出组织ID" json:"from_org_id"`                 // 转出组织ID（NULL表示从厂家出货）
	ToOrgID      *string    `gorm:"column:to_org_id;comment:转入组织ID" json:"to_org_id"`                     // 转入组织ID（NULL表示退回厂家）
	OperatorID   *string    `gorm:"column:operator_id;comment:操作人ID" json:"operator_id"`                  // 操作人ID
	TransferTime *time.Time `gorm:"column:transfer_time;default:now();comment:转移时间" json:"transfer_time"` // 转移时间
	Remark       *string    `gorm:"column:remark;comment:备注" json:"remark"`                               // 备注
	TenantID     string     `gorm:"column:tenant_id;not null;comment:租户ID" json:"tenant_id"`              // 租户ID
	CreatedAt    *time.Time `gorm:"column:created_at;default:now()" json:"created_at"`                    // 创建时间
}

// TableName DeviceOrgTransfer's table name
func (*DeviceOrgTransfer) TableName() string {
	return TableNameDeviceOrgTransfer
}
