// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOrgClosure = "org_closure"

// OrgClosure mapped from table <org_closure>
// 组织闭包表：存储祖先-后代关系，用于子树查询与权限过滤
type OrgClosure struct {
	TenantID     string `gorm:"column:tenant_id;primaryKey;comment:租户ID" json:"tenant_id"`                 // 租户ID
	AncestorID   string `gorm:"column:ancestor_id;primaryKey;comment:祖先组织ID" json:"ancestor_id"`           // 祖先组织ID
	DescendantID string `gorm:"column:descendant_id;primaryKey;comment:后代组织ID（包含自身）" json:"descendant_id"` // 后代组织ID（包含自身）
	Depth        int    `gorm:"column:depth;not null;default:0;comment:层级深度" json:"depth"`                 // 层级深度: 0=自身, 1=直接子节点, 2=孙节点...
}

// TableName OrgClosure's table name
func (*OrgClosure) TableName() string {
	return TableNameOrgClosure
}
