// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrg = "orgs"

// Org mapped from table <orgs>
type Org struct {
	ID            string     `gorm:"column:id;primaryKey;comment:组织ID" json:"id"`                                                     // 组织ID
	Name          string     `gorm:"column:name;not null;comment:组织名称" json:"name"`                                                   // 组织名称
	OrgType       string     `gorm:"column:org_type;not null;comment:组织类型: BMS_FACTORY, PACK_FACTORY, DEALER, STORE" json:"org_type"` // 组织类型
	ParentID      *string    `gorm:"column:parent_id;comment:上级组织ID" json:"parent_id"`                                                // 上级组织ID
	TenantID      string     `gorm:"column:tenant_id;not null;comment:租户ID" json:"tenant_id"`                                         // 租户ID
	ContactPerson *string    `gorm:"column:contact_person" json:"contact_person"`                                                     // 联系人
	Phone         *string    `gorm:"column:phone" json:"phone"`                                                                       // 电话
	Email         *string    `gorm:"column:email" json:"email"`                                                                       // 邮箱
	Province      *string    `gorm:"column:province" json:"province"`                                                                 // 省份
	City          *string    `gorm:"column:city" json:"city"`                                                                         // 城市
	District      *string    `gorm:"column:district" json:"district"`                                                                 // 区县
	Address       *string    `gorm:"column:address" json:"address"`                                                                   // 详细地址
	Status        *string    `gorm:"column:status;default:N;comment:状态: N-正常, F-禁用" json:"status"`                                    // 状态
	CreatedAt     *time.Time `gorm:"column:created_at;default:now()" json:"created_at"`                                               // 创建时间
	UpdatedAt     *time.Time `gorm:"column:updated_at;default:now()" json:"updated_at"`                                               // 更新时间
	Remark        *string    `gorm:"column:remark" json:"remark"`                                                                     // 备注
}

// TableName Org's table name
func (*Org) TableName() string {
	return TableNameOrg
}

// OrgType 常量定义
const (
	OrgTypeBMSFactory  = "BMS_FACTORY"  // BMS 电源板厂家
	OrgTypePACKFactory = "PACK_FACTORY" // PACK 厂家
	OrgTypeDealer      = "DEALER"       // 经销商
	OrgTypeStore       = "STORE"        // 门店
)

// OrgStatus 常量定义
const (
	OrgStatusNormal   = "N" // 正常
	OrgStatusDisabled = "F" // 禁用
)
