// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"project/internal/model"
)

func newBatteryModel(db *gorm.DB, opts ...gen.DOOption) batteryModel {
	_batteryModel := batteryModel{}

	_batteryModel.batteryModelDo.UseDB(db, opts...)
	_batteryModel.batteryModelDo.UseModel(&model.BatteryModel{})

	tableName := _batteryModel.batteryModelDo.TableName()
	_batteryModel.ALL = field.NewAsterisk(tableName)
	_batteryModel.ID = field.NewString(tableName, "id")
	_batteryModel.Name = field.NewString(tableName, "name")
	_batteryModel.VoltageRated = field.NewFloat64(tableName, "voltage_rated")
	_batteryModel.CapacityRated = field.NewFloat64(tableName, "capacity_rated")
	_batteryModel.CellCount = field.NewInt32(tableName, "cell_count")
	_batteryModel.NominalPower = field.NewFloat64(tableName, "nominal_power")
	_batteryModel.WarrantyMonth = field.NewInt32(tableName, "warranty_months")
	_batteryModel.Description = field.NewString(tableName, "description")
	_batteryModel.TenantID = field.NewString(tableName, "tenant_id")
	_batteryModel.CreatedAt = field.NewTime(tableName, "created_at")
	_batteryModel.UpdatedAt = field.NewTime(tableName, "updated_at")

	_batteryModel.fillFieldMap()

	return _batteryModel
}

type batteryModel struct {
	batteryModelDo

	ALL           field.Asterisk
	ID            field.String
	Name          field.String
	VoltageRated  field.Float64
	CapacityRated field.Float64
	CellCount     field.Int32
	NominalPower  field.Float64
	WarrantyMonth field.Int32
	Description   field.String
	TenantID      field.String
	CreatedAt     field.Time
	UpdatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (b batteryModel) Table(newTableName string) *batteryModel {
	b.batteryModelDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b batteryModel) As(alias string) *batteryModel {
	b.batteryModelDo.DO = *(b.batteryModelDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *batteryModel) updateTableName(table string) *batteryModel {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewString(table, "id")
	b.Name = field.NewString(table, "name")
	b.VoltageRated = field.NewFloat64(table, "voltage_rated")
	b.CapacityRated = field.NewFloat64(table, "capacity_rated")
	b.CellCount = field.NewInt32(table, "cell_count")
	b.NominalPower = field.NewFloat64(table, "nominal_power")
	b.WarrantyMonth = field.NewInt32(table, "warranty_months")
	b.Description = field.NewString(table, "description")
	b.TenantID = field.NewString(table, "tenant_id")
	b.CreatedAt = field.NewTime(table, "created_at")
	b.UpdatedAt = field.NewTime(table, "updated_at")

	b.fillFieldMap()

	return b
}

func (b *batteryModel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *batteryModel) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 11)
	b.fieldMap["id"] = b.ID
	b.fieldMap["name"] = b.Name
	b.fieldMap["voltage_rated"] = b.VoltageRated
	b.fieldMap["capacity_rated"] = b.CapacityRated
	b.fieldMap["cell_count"] = b.CellCount
	b.fieldMap["nominal_power"] = b.NominalPower
	b.fieldMap["warranty_months"] = b.WarrantyMonth
	b.fieldMap["description"] = b.Description
	b.fieldMap["tenant_id"] = b.TenantID
	b.fieldMap["created_at"] = b.CreatedAt
	b.fieldMap["updated_at"] = b.UpdatedAt
}

func (b batteryModel) clone(db *gorm.DB) batteryModel {
	b.batteryModelDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b batteryModel) replaceDB(db *gorm.DB) batteryModel {
	b.batteryModelDo.ReplaceDB(db)
	return b
}

type batteryModelDo struct{ gen.DO }

type IBatteryModelDo interface {
	gen.SubQuery
	Debug() IBatteryModelDo
	WithContext(ctx context.Context) IBatteryModelDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IBatteryModelDo
	WriteDB() IBatteryModelDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IBatteryModelDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IBatteryModelDo
	Not(conds ...gen.Condition) IBatteryModelDo
	Or(conds ...gen.Condition) IBatteryModelDo
	Select(conds ...field.Expr) IBatteryModelDo
	Where(conds ...gen.Condition) IBatteryModelDo
	Order(conds ...field.Expr) IBatteryModelDo
	Distinct(cols ...field.Expr) IBatteryModelDo
	Omit(cols ...field.Expr) IBatteryModelDo
	Join(table schema.Tabler, on ...field.Expr) IBatteryModelDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IBatteryModelDo
	RightJoin(table schema.Tabler, on ...field.Expr) IBatteryModelDo
	Group(cols ...field.Expr) IBatteryModelDo
	Having(conds ...gen.Condition) IBatteryModelDo
	Limit(limit int) IBatteryModelDo
	Offset(offset int) IBatteryModelDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IBatteryModelDo
	Unscoped() IBatteryModelDo
	Create(values ...*model.BatteryModel) error
	CreateInBatches(values []*model.BatteryModel, batchSize int) error
	Save(values ...*model.BatteryModel) error
	First() (*model.BatteryModel, error)
	Take() (*model.BatteryModel, error)
	Last() (*model.BatteryModel, error)
	Find() ([]*model.BatteryModel, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BatteryModel, err error)
	FindInBatches(result *[]*model.BatteryModel, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.BatteryModel) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IBatteryModelDo
	Assign(attrs ...field.AssignExpr) IBatteryModelDo
	Joins(fields ...field.RelationField) IBatteryModelDo
	Preload(fields ...field.RelationField) IBatteryModelDo
	FirstOrInit() (*model.BatteryModel, error)
	FirstOrCreate() (*model.BatteryModel, error)
	FindByPage(offset int, limit int) (result []*model.BatteryModel, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IBatteryModelDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (b batteryModelDo) Debug() IBatteryModelDo {
	return b.withDO(b.DO.Debug())
}

func (b batteryModelDo) WithContext(ctx context.Context) IBatteryModelDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b batteryModelDo) ReadDB() IBatteryModelDo {
	return b.Clauses(dbresolver.Read)
}

func (b batteryModelDo) WriteDB() IBatteryModelDo {
	return b.Clauses(dbresolver.Write)
}

func (b batteryModelDo) Session(config *gorm.Session) IBatteryModelDo {
	return b.withDO(b.DO.Session(config))
}

func (b batteryModelDo) Clauses(conds ...clause.Expression) IBatteryModelDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b batteryModelDo) Returning(value interface{}, columns ...string) IBatteryModelDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b batteryModelDo) Not(conds ...gen.Condition) IBatteryModelDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b batteryModelDo) Or(conds ...gen.Condition) IBatteryModelDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b batteryModelDo) Select(conds ...field.Expr) IBatteryModelDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b batteryModelDo) Where(conds ...gen.Condition) IBatteryModelDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b batteryModelDo) Order(conds ...field.Expr) IBatteryModelDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b batteryModelDo) Distinct(cols ...field.Expr) IBatteryModelDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b batteryModelDo) Omit(cols ...field.Expr) IBatteryModelDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b batteryModelDo) Join(table schema.Tabler, on ...field.Expr) IBatteryModelDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b batteryModelDo) LeftJoin(table schema.Tabler, on ...field.Expr) IBatteryModelDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b batteryModelDo) RightJoin(table schema.Tabler, on ...field.Expr) IBatteryModelDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b batteryModelDo) Group(cols ...field.Expr) IBatteryModelDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b batteryModelDo) Having(conds ...gen.Condition) IBatteryModelDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b batteryModelDo) Limit(limit int) IBatteryModelDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b batteryModelDo) Offset(offset int) IBatteryModelDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b batteryModelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IBatteryModelDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b batteryModelDo) Unscoped() IBatteryModelDo {
	return b.withDO(b.DO.Unscoped())
}

func (b batteryModelDo) Create(values ...*model.BatteryModel) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b batteryModelDo) CreateInBatches(values []*model.BatteryModel, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b batteryModelDo) Save(values ...*model.BatteryModel) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b batteryModelDo) First() (*model.BatteryModel, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BatteryModel), nil
	}
}

func (b batteryModelDo) Take() (*model.BatteryModel, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BatteryModel), nil
	}
}

func (b batteryModelDo) Last() (*model.BatteryModel, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BatteryModel), nil
	}
}

func (b batteryModelDo) Find() ([]*model.BatteryModel, error) {
	result, err := b.DO.Find()
	return result.([]*model.BatteryModel), err
}

func (b batteryModelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BatteryModel, err error) {
	buf := make([]*model.BatteryModel, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b batteryModelDo) FindInBatches(result *[]*model.BatteryModel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b batteryModelDo) Attrs(attrs ...field.AssignExpr) IBatteryModelDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b batteryModelDo) Assign(attrs ...field.AssignExpr) IBatteryModelDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b batteryModelDo) Joins(fields ...field.RelationField) IBatteryModelDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b batteryModelDo) Preload(fields ...field.RelationField) IBatteryModelDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b batteryModelDo) FirstOrInit() (*model.BatteryModel, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BatteryModel), nil
	}
}

func (b batteryModelDo) FirstOrCreate() (*model.BatteryModel, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BatteryModel), nil
	}
}

func (b batteryModelDo) FindByPage(offset int, limit int) (result []*model.BatteryModel, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b batteryModelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b batteryModelDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b batteryModelDo) Delete(models ...*model.BatteryModel) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *batteryModelDo) withDO(do gen.Dao) *batteryModelDo {
	b.DO = *do.(*gen.DO)
	return b
}
