// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"project/internal/model"
)

func newDealer(db *gorm.DB, opts ...gen.DOOption) dealer {
	_dealer := dealer{}

	_dealer.dealerDo.UseDB(db, opts...)
	_dealer.dealerDo.UseModel(&model.Dealer{})

	tableName := _dealer.dealerDo.TableName()
	_dealer.ALL = field.NewAsterisk(tableName)
	_dealer.ID = field.NewString(tableName, "id")
	_dealer.Name = field.NewString(tableName, "name")
	_dealer.ContactPerson = field.NewString(tableName, "contact_person")
	_dealer.Phone = field.NewString(tableName, "phone")
	_dealer.Email = field.NewString(tableName, "email")
	_dealer.Province = field.NewString(tableName, "province")
	_dealer.City = field.NewString(tableName, "city")
	_dealer.District = field.NewString(tableName, "district")
	_dealer.Address = field.NewString(tableName, "address")
	_dealer.ParentID = field.NewString(tableName, "parent_id")
	_dealer.TenantID = field.NewString(tableName, "tenant_id")
	_dealer.CreatedAt = field.NewTime(tableName, "created_at")
	_dealer.UpdatedAt = field.NewTime(tableName, "updated_at")
	_dealer.Remark = field.NewString(tableName, "remark")

	_dealer.fillFieldMap()

	return _dealer
}

type dealer struct {
	dealerDo

	ALL           field.Asterisk
	ID            field.String // 经销商ID
	Name          field.String // 经销商名称
	ContactPerson field.String
	Phone         field.String
	Email         field.String
	Province      field.String
	City          field.String
	District      field.String
	Address       field.String
	ParentID      field.String
	TenantID      field.String // 租户ID
	CreatedAt     field.Time
	UpdatedAt     field.Time
	Remark        field.String

	fieldMap map[string]field.Expr
}

func (d dealer) Table(newTableName string) *dealer {
	d.dealerDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d dealer) As(alias string) *dealer {
	d.dealerDo.DO = *(d.dealerDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *dealer) updateTableName(table string) *dealer {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewString(table, "id")
	d.Name = field.NewString(table, "name")
	d.ContactPerson = field.NewString(table, "contact_person")
	d.Phone = field.NewString(table, "phone")
	d.Email = field.NewString(table, "email")
	d.Province = field.NewString(table, "province")
	d.City = field.NewString(table, "city")
	d.District = field.NewString(table, "district")
	d.Address = field.NewString(table, "address")
	d.ParentID = field.NewString(table, "parent_id")
	d.TenantID = field.NewString(table, "tenant_id")
	d.CreatedAt = field.NewTime(table, "created_at")
	d.UpdatedAt = field.NewTime(table, "updated_at")
	d.Remark = field.NewString(table, "remark")

	d.fillFieldMap()

	return d
}

func (d *dealer) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *dealer) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 14)
	d.fieldMap["id"] = d.ID
	d.fieldMap["name"] = d.Name
	d.fieldMap["contact_person"] = d.ContactPerson
	d.fieldMap["phone"] = d.Phone
	d.fieldMap["email"] = d.Email
	d.fieldMap["province"] = d.Province
	d.fieldMap["city"] = d.City
	d.fieldMap["district"] = d.District
	d.fieldMap["address"] = d.Address
	d.fieldMap["parent_id"] = d.ParentID
	d.fieldMap["tenant_id"] = d.TenantID
	d.fieldMap["created_at"] = d.CreatedAt
	d.fieldMap["updated_at"] = d.UpdatedAt
	d.fieldMap["remark"] = d.Remark
}

func (d dealer) clone(db *gorm.DB) dealer {
	d.dealerDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d dealer) replaceDB(db *gorm.DB) dealer {
	d.dealerDo.ReplaceDB(db)
	return d
}

type dealerDo struct{ gen.DO }

type IDealerDo interface {
	gen.SubQuery
	Debug() IDealerDo
	WithContext(ctx context.Context) IDealerDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDealerDo
	WriteDB() IDealerDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDealerDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDealerDo
	Not(conds ...gen.Condition) IDealerDo
	Or(conds ...gen.Condition) IDealerDo
	Select(conds ...field.Expr) IDealerDo
	Where(conds ...gen.Condition) IDealerDo
	Order(conds ...field.Expr) IDealerDo
	Distinct(cols ...field.Expr) IDealerDo
	Omit(cols ...field.Expr) IDealerDo
	Join(table schema.Tabler, on ...field.Expr) IDealerDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDealerDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDealerDo
	Group(cols ...field.Expr) IDealerDo
	Having(conds ...gen.Condition) IDealerDo
	Limit(limit int) IDealerDo
	Offset(offset int) IDealerDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDealerDo
	Unscoped() IDealerDo
	Create(values ...*model.Dealer) error
	CreateInBatches(values []*model.Dealer, batchSize int) error
	Save(values ...*model.Dealer) error
	First() (*model.Dealer, error)
	Take() (*model.Dealer, error)
	Last() (*model.Dealer, error)
	Find() ([]*model.Dealer, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Dealer, err error)
	FindInBatches(result *[]*model.Dealer, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Dealer) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDealerDo
	Assign(attrs ...field.AssignExpr) IDealerDo
	Joins(fields ...field.RelationField) IDealerDo
	Preload(fields ...field.RelationField) IDealerDo
	FirstOrInit() (*model.Dealer, error)
	FirstOrCreate() (*model.Dealer, error)
	FindByPage(offset int, limit int) (result []*model.Dealer, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDealerDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d dealerDo) Debug() IDealerDo {
	return d.withDO(d.DO.Debug())
}

func (d dealerDo) WithContext(ctx context.Context) IDealerDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d dealerDo) ReadDB() IDealerDo {
	return d.Clauses(dbresolver.Read)
}

func (d dealerDo) WriteDB() IDealerDo {
	return d.Clauses(dbresolver.Write)
}

func (d dealerDo) Session(config *gorm.Session) IDealerDo {
	return d.withDO(d.DO.Session(config))
}

func (d dealerDo) Clauses(conds ...clause.Expression) IDealerDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d dealerDo) Returning(value interface{}, columns ...string) IDealerDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d dealerDo) Not(conds ...gen.Condition) IDealerDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d dealerDo) Or(conds ...gen.Condition) IDealerDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d dealerDo) Select(conds ...field.Expr) IDealerDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d dealerDo) Where(conds ...gen.Condition) IDealerDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d dealerDo) Order(conds ...field.Expr) IDealerDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d dealerDo) Distinct(cols ...field.Expr) IDealerDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d dealerDo) Omit(cols ...field.Expr) IDealerDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d dealerDo) Join(table schema.Tabler, on ...field.Expr) IDealerDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d dealerDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDealerDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d dealerDo) RightJoin(table schema.Tabler, on ...field.Expr) IDealerDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d dealerDo) Group(cols ...field.Expr) IDealerDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d dealerDo) Having(conds ...gen.Condition) IDealerDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d dealerDo) Limit(limit int) IDealerDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d dealerDo) Offset(offset int) IDealerDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d dealerDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDealerDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d dealerDo) Unscoped() IDealerDo {
	return d.withDO(d.DO.Unscoped())
}

func (d dealerDo) Create(values ...*model.Dealer) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d dealerDo) CreateInBatches(values []*model.Dealer, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d dealerDo) Save(values ...*model.Dealer) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d dealerDo) First() (*model.Dealer, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Dealer), nil
	}
}

func (d dealerDo) Take() (*model.Dealer, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Dealer), nil
	}
}

func (d dealerDo) Last() (*model.Dealer, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Dealer), nil
	}
}

func (d dealerDo) Find() ([]*model.Dealer, error) {
	result, err := d.DO.Find()
	return result.([]*model.Dealer), err
}

func (d dealerDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Dealer, err error) {
	buf := make([]*model.Dealer, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d dealerDo) FindInBatches(result *[]*model.Dealer, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d dealerDo) Attrs(attrs ...field.AssignExpr) IDealerDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d dealerDo) Assign(attrs ...field.AssignExpr) IDealerDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d dealerDo) Joins(fields ...field.RelationField) IDealerDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d dealerDo) Preload(fields ...field.RelationField) IDealerDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d dealerDo) FirstOrInit() (*model.Dealer, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Dealer), nil
	}
}

func (d dealerDo) FirstOrCreate() (*model.Dealer, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Dealer), nil
	}
}

func (d dealerDo) FindByPage(offset int, limit int) (result []*model.Dealer, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d dealerDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d dealerDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d dealerDo) Delete(models ...*model.Dealer) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *dealerDo) withDO(do gen.Dao) *dealerDo {
	d.DO = *do.(*gen.DO)
	return d
}
