// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"project/internal/model"
)

func newDeviceBattery(db *gorm.DB, opts ...gen.DOOption) deviceBattery {
	_deviceBattery := deviceBattery{}

	_deviceBattery.deviceBatteryDo.UseDB(db, opts...)
	_deviceBattery.deviceBatteryDo.UseModel(&model.DeviceBattery{})

	tableName := _deviceBattery.deviceBatteryDo.TableName()
	_deviceBattery.ALL = field.NewAsterisk(tableName)
	_deviceBattery.DeviceID = field.NewString(tableName, "device_id")
	_deviceBattery.BatteryModelID = field.NewString(tableName, "battery_model_id")
	_deviceBattery.DealerID = field.NewString(tableName, "dealer_id")
	_deviceBattery.OwnerOrgID = field.NewString(tableName, "owner_org_id")
	_deviceBattery.BmsFactoryOrgID = field.NewString(tableName, "bms_factory_org_id")
	_deviceBattery.PackFactoryOrgID = field.NewString(tableName, "pack_factory_org_id")
	_deviceBattery.ProductionDate = field.NewTime(tableName, "production_date")
	_deviceBattery.WarrantyExpireDate = field.NewTime(tableName, "warranty_expire_date")
	_deviceBattery.ActivationDate = field.NewTime(tableName, "activation_date")
	_deviceBattery.ActivationStatus = field.NewString(tableName, "activation_status")
	_deviceBattery.TransferStatus = field.NewString(tableName, "transfer_status")
	_deviceBattery.BatchNumber = field.NewString(tableName, "batch_number")
	_deviceBattery.Soc = field.NewFloat64(tableName, "soc")
	_deviceBattery.Soh = field.NewFloat64(tableName, "soh")
	_deviceBattery.UpdatedAt = field.NewTime(tableName, "updated_at")

	_deviceBattery.fillFieldMap()

	return _deviceBattery
}

type deviceBattery struct {
	deviceBatteryDo

	ALL                field.Asterisk
	DeviceID           field.String
	BatteryModelID     field.String
	DealerID           field.String
	OwnerOrgID         field.String // 当前持有方组织ID
	BmsFactoryOrgID    field.String // BMS板卡出厂方组织ID
	PackFactoryOrgID   field.String // PACK组装方组织ID
	ProductionDate     field.Time
	WarrantyExpireDate field.Time
	ActivationDate     field.Time
	ActivationStatus   field.String // 激活状态: INACTIVE, ACTIVE
	TransferStatus     field.String // 流转状态: FACTORY, DEALER, USER
	BatchNumber        field.String
	Soc                field.Float64
	Soh                field.Float64
	UpdatedAt          field.Time

	fieldMap map[string]field.Expr
}

func (d deviceBattery) Table(newTableName string) *deviceBattery {
	d.deviceBatteryDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d deviceBattery) As(alias string) *deviceBattery {
	d.deviceBatteryDo.DO = *(d.deviceBatteryDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *deviceBattery) updateTableName(table string) *deviceBattery {
	d.ALL = field.NewAsterisk(table)
	d.DeviceID = field.NewString(table, "device_id")
	d.BatteryModelID = field.NewString(table, "battery_model_id")
	d.DealerID = field.NewString(table, "dealer_id")
	d.OwnerOrgID = field.NewString(table, "owner_org_id")
	d.BmsFactoryOrgID = field.NewString(table, "bms_factory_org_id")
	d.PackFactoryOrgID = field.NewString(table, "pack_factory_org_id")
	d.ProductionDate = field.NewTime(table, "production_date")
	d.WarrantyExpireDate = field.NewTime(table, "warranty_expire_date")
	d.ActivationDate = field.NewTime(table, "activation_date")
	d.ActivationStatus = field.NewString(table, "activation_status")
	d.TransferStatus = field.NewString(table, "transfer_status")
	d.BatchNumber = field.NewString(table, "batch_number")
	d.Soc = field.NewFloat64(table, "soc")
	d.Soh = field.NewFloat64(table, "soh")
	d.UpdatedAt = field.NewTime(table, "updated_at")

	d.fillFieldMap()

	return d
}

func (d *deviceBattery) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *deviceBattery) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 15)
	d.fieldMap["device_id"] = d.DeviceID
	d.fieldMap["battery_model_id"] = d.BatteryModelID
	d.fieldMap["dealer_id"] = d.DealerID
	d.fieldMap["owner_org_id"] = d.OwnerOrgID
	d.fieldMap["bms_factory_org_id"] = d.BmsFactoryOrgID
	d.fieldMap["pack_factory_org_id"] = d.PackFactoryOrgID
	d.fieldMap["production_date"] = d.ProductionDate
	d.fieldMap["warranty_expire_date"] = d.WarrantyExpireDate
	d.fieldMap["activation_date"] = d.ActivationDate
	d.fieldMap["activation_status"] = d.ActivationStatus
	d.fieldMap["transfer_status"] = d.TransferStatus
	d.fieldMap["batch_number"] = d.BatchNumber
	d.fieldMap["soc"] = d.Soc
	d.fieldMap["soh"] = d.Soh
	d.fieldMap["updated_at"] = d.UpdatedAt
}

func (d deviceBattery) clone(db *gorm.DB) deviceBattery {
	d.deviceBatteryDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d deviceBattery) replaceDB(db *gorm.DB) deviceBattery {
	d.deviceBatteryDo.ReplaceDB(db)
	return d
}

type deviceBatteryDo struct{ gen.DO }

type IDeviceBatteryDo interface {
	gen.SubQuery
	Debug() IDeviceBatteryDo
	WithContext(ctx context.Context) IDeviceBatteryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDeviceBatteryDo
	WriteDB() IDeviceBatteryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDeviceBatteryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDeviceBatteryDo
	Not(conds ...gen.Condition) IDeviceBatteryDo
	Or(conds ...gen.Condition) IDeviceBatteryDo
	Select(conds ...field.Expr) IDeviceBatteryDo
	Where(conds ...gen.Condition) IDeviceBatteryDo
	Order(conds ...field.Expr) IDeviceBatteryDo
	Distinct(cols ...field.Expr) IDeviceBatteryDo
	Omit(cols ...field.Expr) IDeviceBatteryDo
	Join(table schema.Tabler, on ...field.Expr) IDeviceBatteryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDeviceBatteryDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDeviceBatteryDo
	Group(cols ...field.Expr) IDeviceBatteryDo
	Having(conds ...gen.Condition) IDeviceBatteryDo
	Limit(limit int) IDeviceBatteryDo
	Offset(offset int) IDeviceBatteryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDeviceBatteryDo
	Unscoped() IDeviceBatteryDo
	Create(values ...*model.DeviceBattery) error
	CreateInBatches(values []*model.DeviceBattery, batchSize int) error
	Save(values ...*model.DeviceBattery) error
	First() (*model.DeviceBattery, error)
	Take() (*model.DeviceBattery, error)
	Last() (*model.DeviceBattery, error)
	Find() ([]*model.DeviceBattery, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DeviceBattery, err error)
	FindInBatches(result *[]*model.DeviceBattery, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DeviceBattery) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDeviceBatteryDo
	Assign(attrs ...field.AssignExpr) IDeviceBatteryDo
	Joins(fields ...field.RelationField) IDeviceBatteryDo
	Preload(fields ...field.RelationField) IDeviceBatteryDo
	FirstOrInit() (*model.DeviceBattery, error)
	FirstOrCreate() (*model.DeviceBattery, error)
	FindByPage(offset int, limit int) (result []*model.DeviceBattery, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDeviceBatteryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d deviceBatteryDo) Debug() IDeviceBatteryDo {
	return d.withDO(d.DO.Debug())
}

func (d deviceBatteryDo) WithContext(ctx context.Context) IDeviceBatteryDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d deviceBatteryDo) ReadDB() IDeviceBatteryDo {
	return d.Clauses(dbresolver.Read)
}

func (d deviceBatteryDo) WriteDB() IDeviceBatteryDo {
	return d.Clauses(dbresolver.Write)
}

func (d deviceBatteryDo) Session(config *gorm.Session) IDeviceBatteryDo {
	return d.withDO(d.DO.Session(config))
}

func (d deviceBatteryDo) Clauses(conds ...clause.Expression) IDeviceBatteryDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d deviceBatteryDo) Returning(value interface{}, columns ...string) IDeviceBatteryDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d deviceBatteryDo) Not(conds ...gen.Condition) IDeviceBatteryDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d deviceBatteryDo) Or(conds ...gen.Condition) IDeviceBatteryDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d deviceBatteryDo) Select(conds ...field.Expr) IDeviceBatteryDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d deviceBatteryDo) Where(conds ...gen.Condition) IDeviceBatteryDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d deviceBatteryDo) Order(conds ...field.Expr) IDeviceBatteryDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d deviceBatteryDo) Distinct(cols ...field.Expr) IDeviceBatteryDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d deviceBatteryDo) Omit(cols ...field.Expr) IDeviceBatteryDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d deviceBatteryDo) Join(table schema.Tabler, on ...field.Expr) IDeviceBatteryDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d deviceBatteryDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDeviceBatteryDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d deviceBatteryDo) RightJoin(table schema.Tabler, on ...field.Expr) IDeviceBatteryDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d deviceBatteryDo) Group(cols ...field.Expr) IDeviceBatteryDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d deviceBatteryDo) Having(conds ...gen.Condition) IDeviceBatteryDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d deviceBatteryDo) Limit(limit int) IDeviceBatteryDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d deviceBatteryDo) Offset(offset int) IDeviceBatteryDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d deviceBatteryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDeviceBatteryDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d deviceBatteryDo) Unscoped() IDeviceBatteryDo {
	return d.withDO(d.DO.Unscoped())
}

func (d deviceBatteryDo) Create(values ...*model.DeviceBattery) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d deviceBatteryDo) CreateInBatches(values []*model.DeviceBattery, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d deviceBatteryDo) Save(values ...*model.DeviceBattery) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d deviceBatteryDo) First() (*model.DeviceBattery, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceBattery), nil
	}
}

func (d deviceBatteryDo) Take() (*model.DeviceBattery, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceBattery), nil
	}
}

func (d deviceBatteryDo) Last() (*model.DeviceBattery, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceBattery), nil
	}
}

func (d deviceBatteryDo) Find() ([]*model.DeviceBattery, error) {
	result, err := d.DO.Find()
	return result.([]*model.DeviceBattery), err
}

func (d deviceBatteryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DeviceBattery, err error) {
	buf := make([]*model.DeviceBattery, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d deviceBatteryDo) FindInBatches(result *[]*model.DeviceBattery, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d deviceBatteryDo) Attrs(attrs ...field.AssignExpr) IDeviceBatteryDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d deviceBatteryDo) Assign(attrs ...field.AssignExpr) IDeviceBatteryDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d deviceBatteryDo) Joins(fields ...field.RelationField) IDeviceBatteryDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d deviceBatteryDo) Preload(fields ...field.RelationField) IDeviceBatteryDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d deviceBatteryDo) FirstOrInit() (*model.DeviceBattery, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceBattery), nil
	}
}

func (d deviceBatteryDo) FirstOrCreate() (*model.DeviceBattery, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceBattery), nil
	}
}

func (d deviceBatteryDo) FindByPage(offset int, limit int) (result []*model.DeviceBattery, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d deviceBatteryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d deviceBatteryDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d deviceBatteryDo) Delete(models ...*model.DeviceBattery) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *deviceBatteryDo) withDO(do gen.Dao) *deviceBatteryDo {
	d.DO = *do.(*gen.DO)
	return d
}
