// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"project/internal/model"
)

func newDeviceOrgTransfer(db *gorm.DB, opts ...gen.DOOption) deviceOrgTransfer {
	_deviceOrgTransfer := deviceOrgTransfer{}

	_deviceOrgTransfer.deviceOrgTransferDo.UseDB(db, opts...)
	_deviceOrgTransfer.deviceOrgTransferDo.UseModel(&model.DeviceOrgTransfer{})

	tableName := _deviceOrgTransfer.deviceOrgTransferDo.TableName()
	_deviceOrgTransfer.ALL = field.NewAsterisk(tableName)
	_deviceOrgTransfer.ID = field.NewString(tableName, "id")
	_deviceOrgTransfer.DeviceID = field.NewString(tableName, "device_id")
	_deviceOrgTransfer.FromOrgID = field.NewString(tableName, "from_org_id")
	_deviceOrgTransfer.ToOrgID = field.NewString(tableName, "to_org_id")
	_deviceOrgTransfer.OperatorID = field.NewString(tableName, "operator_id")
	_deviceOrgTransfer.TransferTime = field.NewTime(tableName, "transfer_time")
	_deviceOrgTransfer.Remark = field.NewString(tableName, "remark")
	_deviceOrgTransfer.TenantID = field.NewString(tableName, "tenant_id")
	_deviceOrgTransfer.CreatedAt = field.NewTime(tableName, "created_at")

	_deviceOrgTransfer.fillFieldMap()

	return _deviceOrgTransfer
}

type deviceOrgTransfer struct {
	deviceOrgTransferDo

	ALL          field.Asterisk
	ID           field.String // 记录ID
	DeviceID     field.String // 设备ID
	FromOrgID    field.String // 转出组织ID
	ToOrgID      field.String // 转入组织ID
	OperatorID   field.String // 操作人ID
	TransferTime field.Time   // 转移时间
	Remark       field.String // 备注
	TenantID     field.String // 租户ID
	CreatedAt    field.Time   // 创建时间

	fieldMap map[string]field.Expr
}

func (d deviceOrgTransfer) Table(newTableName string) *deviceOrgTransfer {
	d.deviceOrgTransferDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d deviceOrgTransfer) As(alias string) *deviceOrgTransfer {
	d.deviceOrgTransferDo.DO = *(d.deviceOrgTransferDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *deviceOrgTransfer) updateTableName(table string) *deviceOrgTransfer {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewString(table, "id")
	d.DeviceID = field.NewString(table, "device_id")
	d.FromOrgID = field.NewString(table, "from_org_id")
	d.ToOrgID = field.NewString(table, "to_org_id")
	d.OperatorID = field.NewString(table, "operator_id")
	d.TransferTime = field.NewTime(table, "transfer_time")
	d.Remark = field.NewString(table, "remark")
	d.TenantID = field.NewString(table, "tenant_id")
	d.CreatedAt = field.NewTime(table, "created_at")

	d.fillFieldMap()

	return d
}

func (d *deviceOrgTransfer) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *deviceOrgTransfer) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 9)
	d.fieldMap["id"] = d.ID
	d.fieldMap["device_id"] = d.DeviceID
	d.fieldMap["from_org_id"] = d.FromOrgID
	d.fieldMap["to_org_id"] = d.ToOrgID
	d.fieldMap["operator_id"] = d.OperatorID
	d.fieldMap["transfer_time"] = d.TransferTime
	d.fieldMap["remark"] = d.Remark
	d.fieldMap["tenant_id"] = d.TenantID
	d.fieldMap["created_at"] = d.CreatedAt
}

func (d deviceOrgTransfer) clone(db *gorm.DB) deviceOrgTransfer {
	d.deviceOrgTransferDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d deviceOrgTransfer) replaceDB(db *gorm.DB) deviceOrgTransfer {
	d.deviceOrgTransferDo.ReplaceDB(db)
	return d
}

type deviceOrgTransferDo struct{ gen.DO }

type IDeviceOrgTransferDo interface {
	gen.SubQuery
	Debug() IDeviceOrgTransferDo
	WithContext(ctx context.Context) IDeviceOrgTransferDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDeviceOrgTransferDo
	WriteDB() IDeviceOrgTransferDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDeviceOrgTransferDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDeviceOrgTransferDo
	Not(conds ...gen.Condition) IDeviceOrgTransferDo
	Or(conds ...gen.Condition) IDeviceOrgTransferDo
	Select(conds ...field.Expr) IDeviceOrgTransferDo
	Where(conds ...gen.Condition) IDeviceOrgTransferDo
	Order(conds ...field.Expr) IDeviceOrgTransferDo
	Distinct(cols ...field.Expr) IDeviceOrgTransferDo
	Omit(cols ...field.Expr) IDeviceOrgTransferDo
	Join(table schema.Tabler, on ...field.Expr) IDeviceOrgTransferDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDeviceOrgTransferDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDeviceOrgTransferDo
	Group(cols ...field.Expr) IDeviceOrgTransferDo
	Having(conds ...gen.Condition) IDeviceOrgTransferDo
	Limit(limit int) IDeviceOrgTransferDo
	Offset(offset int) IDeviceOrgTransferDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDeviceOrgTransferDo
	Unscoped() IDeviceOrgTransferDo
	Create(values ...*model.DeviceOrgTransfer) error
	CreateInBatches(values []*model.DeviceOrgTransfer, batchSize int) error
	Save(values ...*model.DeviceOrgTransfer) error
	First() (*model.DeviceOrgTransfer, error)
	Take() (*model.DeviceOrgTransfer, error)
	Last() (*model.DeviceOrgTransfer, error)
	Find() ([]*model.DeviceOrgTransfer, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DeviceOrgTransfer, err error)
	FindInBatches(result *[]*model.DeviceOrgTransfer, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DeviceOrgTransfer) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDeviceOrgTransferDo
	Assign(attrs ...field.AssignExpr) IDeviceOrgTransferDo
	Joins(fields ...field.RelationField) IDeviceOrgTransferDo
	Preload(fields ...field.RelationField) IDeviceOrgTransferDo
	FirstOrInit() (*model.DeviceOrgTransfer, error)
	FirstOrCreate() (*model.DeviceOrgTransfer, error)
	FindByPage(offset int, limit int) (result []*model.DeviceOrgTransfer, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDeviceOrgTransferDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d deviceOrgTransferDo) Debug() IDeviceOrgTransferDo {
	return d.withDO(d.DO.Debug())
}

func (d deviceOrgTransferDo) WithContext(ctx context.Context) IDeviceOrgTransferDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d deviceOrgTransferDo) ReadDB() IDeviceOrgTransferDo {
	return d.Clauses(dbresolver.Read)
}

func (d deviceOrgTransferDo) WriteDB() IDeviceOrgTransferDo {
	return d.Clauses(dbresolver.Write)
}

func (d deviceOrgTransferDo) Session(config *gorm.Session) IDeviceOrgTransferDo {
	return d.withDO(d.DO.Session(config))
}

func (d deviceOrgTransferDo) Clauses(conds ...clause.Expression) IDeviceOrgTransferDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d deviceOrgTransferDo) Returning(value interface{}, columns ...string) IDeviceOrgTransferDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d deviceOrgTransferDo) Not(conds ...gen.Condition) IDeviceOrgTransferDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d deviceOrgTransferDo) Or(conds ...gen.Condition) IDeviceOrgTransferDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d deviceOrgTransferDo) Select(conds ...field.Expr) IDeviceOrgTransferDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d deviceOrgTransferDo) Where(conds ...gen.Condition) IDeviceOrgTransferDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d deviceOrgTransferDo) Order(conds ...field.Expr) IDeviceOrgTransferDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d deviceOrgTransferDo) Distinct(cols ...field.Expr) IDeviceOrgTransferDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d deviceOrgTransferDo) Omit(cols ...field.Expr) IDeviceOrgTransferDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d deviceOrgTransferDo) Join(table schema.Tabler, on ...field.Expr) IDeviceOrgTransferDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d deviceOrgTransferDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDeviceOrgTransferDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d deviceOrgTransferDo) RightJoin(table schema.Tabler, on ...field.Expr) IDeviceOrgTransferDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d deviceOrgTransferDo) Group(cols ...field.Expr) IDeviceOrgTransferDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d deviceOrgTransferDo) Having(conds ...gen.Condition) IDeviceOrgTransferDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d deviceOrgTransferDo) Limit(limit int) IDeviceOrgTransferDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d deviceOrgTransferDo) Offset(offset int) IDeviceOrgTransferDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d deviceOrgTransferDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDeviceOrgTransferDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d deviceOrgTransferDo) Unscoped() IDeviceOrgTransferDo {
	return d.withDO(d.DO.Unscoped())
}

func (d deviceOrgTransferDo) Create(values ...*model.DeviceOrgTransfer) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d deviceOrgTransferDo) CreateInBatches(values []*model.DeviceOrgTransfer, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d deviceOrgTransferDo) Save(values ...*model.DeviceOrgTransfer) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d deviceOrgTransferDo) First() (*model.DeviceOrgTransfer, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceOrgTransfer), nil
	}
}

func (d deviceOrgTransferDo) Take() (*model.DeviceOrgTransfer, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceOrgTransfer), nil
	}
}

func (d deviceOrgTransferDo) Last() (*model.DeviceOrgTransfer, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceOrgTransfer), nil
	}
}

func (d deviceOrgTransferDo) Find() ([]*model.DeviceOrgTransfer, error) {
	result, err := d.DO.Find()
	return result.([]*model.DeviceOrgTransfer), err
}

func (d deviceOrgTransferDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DeviceOrgTransfer, err error) {
	buf := make([]*model.DeviceOrgTransfer, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d deviceOrgTransferDo) FindInBatches(result *[]*model.DeviceOrgTransfer, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d deviceOrgTransferDo) Attrs(attrs ...field.AssignExpr) IDeviceOrgTransferDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d deviceOrgTransferDo) Assign(attrs ...field.AssignExpr) IDeviceOrgTransferDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d deviceOrgTransferDo) Joins(fields ...field.RelationField) IDeviceOrgTransferDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d deviceOrgTransferDo) Preload(fields ...field.RelationField) IDeviceOrgTransferDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d deviceOrgTransferDo) FirstOrInit() (*model.DeviceOrgTransfer, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceOrgTransfer), nil
	}
}

func (d deviceOrgTransferDo) FirstOrCreate() (*model.DeviceOrgTransfer, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceOrgTransfer), nil
	}
}

func (d deviceOrgTransferDo) FindByPage(offset int, limit int) (result []*model.DeviceOrgTransfer, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d deviceOrgTransferDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d deviceOrgTransferDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d deviceOrgTransferDo) Delete(models ...*model.DeviceOrgTransfer) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *deviceOrgTransferDo) withDO(do gen.Dao) *deviceOrgTransferDo {
	d.DO = *do.(*gen.DO)
	return d
}
