// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"project/internal/model"
)

func newDeviceTransfer(db *gorm.DB, opts ...gen.DOOption) deviceTransfer {
	_deviceTransfer := deviceTransfer{}

	_deviceTransfer.deviceTransferDo.UseDB(db, opts...)
	_deviceTransfer.deviceTransferDo.UseModel(&model.DeviceTransfer{})

	tableName := _deviceTransfer.deviceTransferDo.TableName()
	_deviceTransfer.ALL = field.NewAsterisk(tableName)
	_deviceTransfer.ID = field.NewString(tableName, "id")
	_deviceTransfer.DeviceID = field.NewString(tableName, "device_id")
	_deviceTransfer.FromDealerID = field.NewString(tableName, "from_dealer_id")
	_deviceTransfer.ToDealerID = field.NewString(tableName, "to_dealer_id")
	_deviceTransfer.OperatorID = field.NewString(tableName, "operator_id")
	_deviceTransfer.TransferTime = field.NewTime(tableName, "transfer_time")
	_deviceTransfer.Remark = field.NewString(tableName, "remark")
	_deviceTransfer.TenantID = field.NewString(tableName, "tenant_id")

	_deviceTransfer.fillFieldMap()

	return _deviceTransfer
}

type deviceTransfer struct {
	deviceTransferDo

	ALL          field.Asterisk
	ID           field.String
	DeviceID     field.String
	FromDealerID field.String
	ToDealerID   field.String
	OperatorID   field.String
	TransferTime field.Time
	Remark       field.String
	TenantID     field.String

	fieldMap map[string]field.Expr
}

func (d deviceTransfer) Table(newTableName string) *deviceTransfer {
	d.deviceTransferDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d deviceTransfer) As(alias string) *deviceTransfer {
	d.deviceTransferDo.DO = *(d.deviceTransferDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *deviceTransfer) updateTableName(table string) *deviceTransfer {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewString(table, "id")
	d.DeviceID = field.NewString(table, "device_id")
	d.FromDealerID = field.NewString(table, "from_dealer_id")
	d.ToDealerID = field.NewString(table, "to_dealer_id")
	d.OperatorID = field.NewString(table, "operator_id")
	d.TransferTime = field.NewTime(table, "transfer_time")
	d.Remark = field.NewString(table, "remark")
	d.TenantID = field.NewString(table, "tenant_id")

	d.fillFieldMap()

	return d
}

func (d *deviceTransfer) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *deviceTransfer) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 8)
	d.fieldMap["id"] = d.ID
	d.fieldMap["device_id"] = d.DeviceID
	d.fieldMap["from_dealer_id"] = d.FromDealerID
	d.fieldMap["to_dealer_id"] = d.ToDealerID
	d.fieldMap["operator_id"] = d.OperatorID
	d.fieldMap["transfer_time"] = d.TransferTime
	d.fieldMap["remark"] = d.Remark
	d.fieldMap["tenant_id"] = d.TenantID
}

func (d deviceTransfer) clone(db *gorm.DB) deviceTransfer {
	d.deviceTransferDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d deviceTransfer) replaceDB(db *gorm.DB) deviceTransfer {
	d.deviceTransferDo.ReplaceDB(db)
	return d
}

type deviceTransferDo struct{ gen.DO }

type IDeviceTransferDo interface {
	gen.SubQuery
	Debug() IDeviceTransferDo
	WithContext(ctx context.Context) IDeviceTransferDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDeviceTransferDo
	WriteDB() IDeviceTransferDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDeviceTransferDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDeviceTransferDo
	Not(conds ...gen.Condition) IDeviceTransferDo
	Or(conds ...gen.Condition) IDeviceTransferDo
	Select(conds ...field.Expr) IDeviceTransferDo
	Where(conds ...gen.Condition) IDeviceTransferDo
	Order(conds ...field.Expr) IDeviceTransferDo
	Distinct(cols ...field.Expr) IDeviceTransferDo
	Omit(cols ...field.Expr) IDeviceTransferDo
	Join(table schema.Tabler, on ...field.Expr) IDeviceTransferDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDeviceTransferDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDeviceTransferDo
	Group(cols ...field.Expr) IDeviceTransferDo
	Having(conds ...gen.Condition) IDeviceTransferDo
	Limit(limit int) IDeviceTransferDo
	Offset(offset int) IDeviceTransferDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDeviceTransferDo
	Unscoped() IDeviceTransferDo
	Create(values ...*model.DeviceTransfer) error
	CreateInBatches(values []*model.DeviceTransfer, batchSize int) error
	Save(values ...*model.DeviceTransfer) error
	First() (*model.DeviceTransfer, error)
	Take() (*model.DeviceTransfer, error)
	Last() (*model.DeviceTransfer, error)
	Find() ([]*model.DeviceTransfer, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DeviceTransfer, err error)
	FindInBatches(result *[]*model.DeviceTransfer, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DeviceTransfer) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDeviceTransferDo
	Assign(attrs ...field.AssignExpr) IDeviceTransferDo
	Joins(fields ...field.RelationField) IDeviceTransferDo
	Preload(fields ...field.RelationField) IDeviceTransferDo
	FirstOrInit() (*model.DeviceTransfer, error)
	FirstOrCreate() (*model.DeviceTransfer, error)
	FindByPage(offset int, limit int) (result []*model.DeviceTransfer, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDeviceTransferDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d deviceTransferDo) Debug() IDeviceTransferDo {
	return d.withDO(d.DO.Debug())
}

func (d deviceTransferDo) WithContext(ctx context.Context) IDeviceTransferDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d deviceTransferDo) ReadDB() IDeviceTransferDo {
	return d.Clauses(dbresolver.Read)
}

func (d deviceTransferDo) WriteDB() IDeviceTransferDo {
	return d.Clauses(dbresolver.Write)
}

func (d deviceTransferDo) Session(config *gorm.Session) IDeviceTransferDo {
	return d.withDO(d.DO.Session(config))
}

func (d deviceTransferDo) Clauses(conds ...clause.Expression) IDeviceTransferDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d deviceTransferDo) Returning(value interface{}, columns ...string) IDeviceTransferDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d deviceTransferDo) Not(conds ...gen.Condition) IDeviceTransferDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d deviceTransferDo) Or(conds ...gen.Condition) IDeviceTransferDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d deviceTransferDo) Select(conds ...field.Expr) IDeviceTransferDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d deviceTransferDo) Where(conds ...gen.Condition) IDeviceTransferDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d deviceTransferDo) Order(conds ...field.Expr) IDeviceTransferDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d deviceTransferDo) Distinct(cols ...field.Expr) IDeviceTransferDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d deviceTransferDo) Omit(cols ...field.Expr) IDeviceTransferDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d deviceTransferDo) Join(table schema.Tabler, on ...field.Expr) IDeviceTransferDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d deviceTransferDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDeviceTransferDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d deviceTransferDo) RightJoin(table schema.Tabler, on ...field.Expr) IDeviceTransferDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d deviceTransferDo) Group(cols ...field.Expr) IDeviceTransferDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d deviceTransferDo) Having(conds ...gen.Condition) IDeviceTransferDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d deviceTransferDo) Limit(limit int) IDeviceTransferDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d deviceTransferDo) Offset(offset int) IDeviceTransferDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d deviceTransferDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDeviceTransferDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d deviceTransferDo) Unscoped() IDeviceTransferDo {
	return d.withDO(d.DO.Unscoped())
}

func (d deviceTransferDo) Create(values ...*model.DeviceTransfer) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d deviceTransferDo) CreateInBatches(values []*model.DeviceTransfer, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d deviceTransferDo) Save(values ...*model.DeviceTransfer) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d deviceTransferDo) First() (*model.DeviceTransfer, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceTransfer), nil
	}
}

func (d deviceTransferDo) Take() (*model.DeviceTransfer, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceTransfer), nil
	}
}

func (d deviceTransferDo) Last() (*model.DeviceTransfer, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceTransfer), nil
	}
}

func (d deviceTransferDo) Find() ([]*model.DeviceTransfer, error) {
	result, err := d.DO.Find()
	return result.([]*model.DeviceTransfer), err
}

func (d deviceTransferDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DeviceTransfer, err error) {
	buf := make([]*model.DeviceTransfer, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d deviceTransferDo) FindInBatches(result *[]*model.DeviceTransfer, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d deviceTransferDo) Attrs(attrs ...field.AssignExpr) IDeviceTransferDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d deviceTransferDo) Assign(attrs ...field.AssignExpr) IDeviceTransferDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d deviceTransferDo) Joins(fields ...field.RelationField) IDeviceTransferDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d deviceTransferDo) Preload(fields ...field.RelationField) IDeviceTransferDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d deviceTransferDo) FirstOrInit() (*model.DeviceTransfer, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceTransfer), nil
	}
}

func (d deviceTransferDo) FirstOrCreate() (*model.DeviceTransfer, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceTransfer), nil
	}
}

func (d deviceTransferDo) FindByPage(offset int, limit int) (result []*model.DeviceTransfer, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d deviceTransferDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d deviceTransferDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d deviceTransferDo) Delete(models ...*model.DeviceTransfer) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *deviceTransferDo) withDO(do gen.Dao) *deviceTransferDo {
	d.DO = *do.(*gen.DO)
	return d
}
