// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"project/internal/model"
)

func newDeviceUserBinding(db *gorm.DB, opts ...gen.DOOption) deviceUserBinding {
	_deviceUserBinding := deviceUserBinding{}

	_deviceUserBinding.deviceUserBindingDo.UseDB(db, opts...)
	_deviceUserBinding.deviceUserBindingDo.UseModel(&model.DeviceUserBinding{})

	tableName := _deviceUserBinding.deviceUserBindingDo.TableName()
	_deviceUserBinding.ALL = field.NewAsterisk(tableName)
	_deviceUserBinding.ID = field.NewString(tableName, "id")
	_deviceUserBinding.UserID = field.NewString(tableName, "user_id")
	_deviceUserBinding.DeviceID = field.NewString(tableName, "device_id")
	_deviceUserBinding.BindingTime = field.NewTime(tableName, "binding_time")
	_deviceUserBinding.IsOwner = field.NewBool(tableName, "is_owner")
	_deviceUserBinding.Remark = field.NewString(tableName, "remark")

	_deviceUserBinding.fillFieldMap()

	return _deviceUserBinding
}

type deviceUserBinding struct {
	deviceUserBindingDo

	ALL         field.Asterisk
	ID          field.String
	UserID      field.String
	DeviceID    field.String
	BindingTime field.Time
	IsOwner     field.Bool
	Remark      field.String

	fieldMap map[string]field.Expr
}

func (d deviceUserBinding) Table(newTableName string) *deviceUserBinding {
	d.deviceUserBindingDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d deviceUserBinding) As(alias string) *deviceUserBinding {
	d.deviceUserBindingDo.DO = *(d.deviceUserBindingDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *deviceUserBinding) updateTableName(table string) *deviceUserBinding {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewString(table, "id")
	d.UserID = field.NewString(table, "user_id")
	d.DeviceID = field.NewString(table, "device_id")
	d.BindingTime = field.NewTime(table, "binding_time")
	d.IsOwner = field.NewBool(table, "is_owner")
	d.Remark = field.NewString(table, "remark")

	d.fillFieldMap()

	return d
}

func (d *deviceUserBinding) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *deviceUserBinding) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 6)
	d.fieldMap["id"] = d.ID
	d.fieldMap["user_id"] = d.UserID
	d.fieldMap["device_id"] = d.DeviceID
	d.fieldMap["binding_time"] = d.BindingTime
	d.fieldMap["is_owner"] = d.IsOwner
	d.fieldMap["remark"] = d.Remark
}

func (d deviceUserBinding) clone(db *gorm.DB) deviceUserBinding {
	d.deviceUserBindingDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d deviceUserBinding) replaceDB(db *gorm.DB) deviceUserBinding {
	d.deviceUserBindingDo.ReplaceDB(db)
	return d
}

type deviceUserBindingDo struct{ gen.DO }

type IDeviceUserBindingDo interface {
	gen.SubQuery
	Debug() IDeviceUserBindingDo
	WithContext(ctx context.Context) IDeviceUserBindingDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDeviceUserBindingDo
	WriteDB() IDeviceUserBindingDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDeviceUserBindingDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDeviceUserBindingDo
	Not(conds ...gen.Condition) IDeviceUserBindingDo
	Or(conds ...gen.Condition) IDeviceUserBindingDo
	Select(conds ...field.Expr) IDeviceUserBindingDo
	Where(conds ...gen.Condition) IDeviceUserBindingDo
	Order(conds ...field.Expr) IDeviceUserBindingDo
	Distinct(cols ...field.Expr) IDeviceUserBindingDo
	Omit(cols ...field.Expr) IDeviceUserBindingDo
	Join(table schema.Tabler, on ...field.Expr) IDeviceUserBindingDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDeviceUserBindingDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDeviceUserBindingDo
	Group(cols ...field.Expr) IDeviceUserBindingDo
	Having(conds ...gen.Condition) IDeviceUserBindingDo
	Limit(limit int) IDeviceUserBindingDo
	Offset(offset int) IDeviceUserBindingDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDeviceUserBindingDo
	Unscoped() IDeviceUserBindingDo
	Create(values ...*model.DeviceUserBinding) error
	CreateInBatches(values []*model.DeviceUserBinding, batchSize int) error
	Save(values ...*model.DeviceUserBinding) error
	First() (*model.DeviceUserBinding, error)
	Take() (*model.DeviceUserBinding, error)
	Last() (*model.DeviceUserBinding, error)
	Find() ([]*model.DeviceUserBinding, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DeviceUserBinding, err error)
	FindInBatches(result *[]*model.DeviceUserBinding, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DeviceUserBinding) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDeviceUserBindingDo
	Assign(attrs ...field.AssignExpr) IDeviceUserBindingDo
	Joins(fields ...field.RelationField) IDeviceUserBindingDo
	Preload(fields ...field.RelationField) IDeviceUserBindingDo
	FirstOrInit() (*model.DeviceUserBinding, error)
	FirstOrCreate() (*model.DeviceUserBinding, error)
	FindByPage(offset int, limit int) (result []*model.DeviceUserBinding, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDeviceUserBindingDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d deviceUserBindingDo) Debug() IDeviceUserBindingDo {
	return d.withDO(d.DO.Debug())
}

func (d deviceUserBindingDo) WithContext(ctx context.Context) IDeviceUserBindingDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d deviceUserBindingDo) ReadDB() IDeviceUserBindingDo {
	return d.Clauses(dbresolver.Read)
}

func (d deviceUserBindingDo) WriteDB() IDeviceUserBindingDo {
	return d.Clauses(dbresolver.Write)
}

func (d deviceUserBindingDo) Session(config *gorm.Session) IDeviceUserBindingDo {
	return d.withDO(d.DO.Session(config))
}

func (d deviceUserBindingDo) Clauses(conds ...clause.Expression) IDeviceUserBindingDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d deviceUserBindingDo) Returning(value interface{}, columns ...string) IDeviceUserBindingDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d deviceUserBindingDo) Not(conds ...gen.Condition) IDeviceUserBindingDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d deviceUserBindingDo) Or(conds ...gen.Condition) IDeviceUserBindingDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d deviceUserBindingDo) Select(conds ...field.Expr) IDeviceUserBindingDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d deviceUserBindingDo) Where(conds ...gen.Condition) IDeviceUserBindingDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d deviceUserBindingDo) Order(conds ...field.Expr) IDeviceUserBindingDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d deviceUserBindingDo) Distinct(cols ...field.Expr) IDeviceUserBindingDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d deviceUserBindingDo) Omit(cols ...field.Expr) IDeviceUserBindingDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d deviceUserBindingDo) Join(table schema.Tabler, on ...field.Expr) IDeviceUserBindingDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d deviceUserBindingDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDeviceUserBindingDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d deviceUserBindingDo) RightJoin(table schema.Tabler, on ...field.Expr) IDeviceUserBindingDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d deviceUserBindingDo) Group(cols ...field.Expr) IDeviceUserBindingDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d deviceUserBindingDo) Having(conds ...gen.Condition) IDeviceUserBindingDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d deviceUserBindingDo) Limit(limit int) IDeviceUserBindingDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d deviceUserBindingDo) Offset(offset int) IDeviceUserBindingDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d deviceUserBindingDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDeviceUserBindingDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d deviceUserBindingDo) Unscoped() IDeviceUserBindingDo {
	return d.withDO(d.DO.Unscoped())
}

func (d deviceUserBindingDo) Create(values ...*model.DeviceUserBinding) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d deviceUserBindingDo) CreateInBatches(values []*model.DeviceUserBinding, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d deviceUserBindingDo) Save(values ...*model.DeviceUserBinding) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d deviceUserBindingDo) First() (*model.DeviceUserBinding, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceUserBinding), nil
	}
}

func (d deviceUserBindingDo) Take() (*model.DeviceUserBinding, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceUserBinding), nil
	}
}

func (d deviceUserBindingDo) Last() (*model.DeviceUserBinding, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceUserBinding), nil
	}
}

func (d deviceUserBindingDo) Find() ([]*model.DeviceUserBinding, error) {
	result, err := d.DO.Find()
	return result.([]*model.DeviceUserBinding), err
}

func (d deviceUserBindingDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DeviceUserBinding, err error) {
	buf := make([]*model.DeviceUserBinding, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d deviceUserBindingDo) FindInBatches(result *[]*model.DeviceUserBinding, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d deviceUserBindingDo) Attrs(attrs ...field.AssignExpr) IDeviceUserBindingDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d deviceUserBindingDo) Assign(attrs ...field.AssignExpr) IDeviceUserBindingDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d deviceUserBindingDo) Joins(fields ...field.RelationField) IDeviceUserBindingDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d deviceUserBindingDo) Preload(fields ...field.RelationField) IDeviceUserBindingDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d deviceUserBindingDo) FirstOrInit() (*model.DeviceUserBinding, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceUserBinding), nil
	}
}

func (d deviceUserBindingDo) FirstOrCreate() (*model.DeviceUserBinding, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceUserBinding), nil
	}
}

func (d deviceUserBindingDo) FindByPage(offset int, limit int) (result []*model.DeviceUserBinding, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d deviceUserBindingDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d deviceUserBindingDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d deviceUserBindingDo) Delete(models ...*model.DeviceUserBinding) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *deviceUserBindingDo) withDO(do gen.Dao) *deviceUserBindingDo {
	d.DO = *do.(*gen.DO)
	return d
}
