// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"project/internal/model"
)

func newOrg(db *gorm.DB, opts ...gen.DOOption) org {
	_org := org{}

	_org.orgDo.UseDB(db, opts...)
	_org.orgDo.UseModel(&model.Org{})

	tableName := _org.orgDo.TableName()
	_org.ALL = field.NewAsterisk(tableName)
	_org.ID = field.NewString(tableName, "id")
	_org.Name = field.NewString(tableName, "name")
	_org.OrgType = field.NewString(tableName, "org_type")
	_org.ParentID = field.NewString(tableName, "parent_id")
	_org.TenantID = field.NewString(tableName, "tenant_id")
	_org.ContactPerson = field.NewString(tableName, "contact_person")
	_org.Phone = field.NewString(tableName, "phone")
	_org.Email = field.NewString(tableName, "email")
	_org.Province = field.NewString(tableName, "province")
	_org.City = field.NewString(tableName, "city")
	_org.District = field.NewString(tableName, "district")
	_org.Address = field.NewString(tableName, "address")
	_org.Status = field.NewString(tableName, "status")
	_org.CreatedAt = field.NewTime(tableName, "created_at")
	_org.UpdatedAt = field.NewTime(tableName, "updated_at")
	_org.Remark = field.NewString(tableName, "remark")

	_org.fillFieldMap()

	return _org
}

type org struct {
	orgDo

	ALL           field.Asterisk
	ID            field.String // 组织ID
	Name          field.String // 组织名称
	OrgType       field.String // 组织类型
	ParentID      field.String // 上级组织ID
	TenantID      field.String // 租户ID
	ContactPerson field.String // 联系人
	Phone         field.String // 电话
	Email         field.String // 邮箱
	Province      field.String // 省份
	City          field.String // 城市
	District      field.String // 区县
	Address       field.String // 详细地址
	Status        field.String // 状态
	CreatedAt     field.Time   // 创建时间
	UpdatedAt     field.Time   // 更新时间
	Remark        field.String // 备注

	fieldMap map[string]field.Expr
}

func (o org) Table(newTableName string) *org {
	o.orgDo.UseTable(newTableName)
	return o.updateTableName(newTableName)
}

func (o org) As(alias string) *org {
	o.orgDo.DO = *(o.orgDo.As(alias).(*gen.DO))
	return o.updateTableName(alias)
}

func (o *org) updateTableName(table string) *org {
	o.ALL = field.NewAsterisk(table)
	o.ID = field.NewString(table, "id")
	o.Name = field.NewString(table, "name")
	o.OrgType = field.NewString(table, "org_type")
	o.ParentID = field.NewString(table, "parent_id")
	o.TenantID = field.NewString(table, "tenant_id")
	o.ContactPerson = field.NewString(table, "contact_person")
	o.Phone = field.NewString(table, "phone")
	o.Email = field.NewString(table, "email")
	o.Province = field.NewString(table, "province")
	o.City = field.NewString(table, "city")
	o.District = field.NewString(table, "district")
	o.Address = field.NewString(table, "address")
	o.Status = field.NewString(table, "status")
	o.CreatedAt = field.NewTime(table, "created_at")
	o.UpdatedAt = field.NewTime(table, "updated_at")
	o.Remark = field.NewString(table, "remark")

	o.fillFieldMap()

	return o
}

func (o *org) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := o.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (o *org) fillFieldMap() {
	o.fieldMap = make(map[string]field.Expr, 16)
	o.fieldMap["id"] = o.ID
	o.fieldMap["name"] = o.Name
	o.fieldMap["org_type"] = o.OrgType
	o.fieldMap["parent_id"] = o.ParentID
	o.fieldMap["tenant_id"] = o.TenantID
	o.fieldMap["contact_person"] = o.ContactPerson
	o.fieldMap["phone"] = o.Phone
	o.fieldMap["email"] = o.Email
	o.fieldMap["province"] = o.Province
	o.fieldMap["city"] = o.City
	o.fieldMap["district"] = o.District
	o.fieldMap["address"] = o.Address
	o.fieldMap["status"] = o.Status
	o.fieldMap["created_at"] = o.CreatedAt
	o.fieldMap["updated_at"] = o.UpdatedAt
	o.fieldMap["remark"] = o.Remark
}

func (o org) clone(db *gorm.DB) org {
	o.orgDo.ReplaceConnPool(db.Statement.ConnPool)
	return o
}

func (o org) replaceDB(db *gorm.DB) org {
	o.orgDo.ReplaceDB(db)
	return o
}

type orgDo struct{ gen.DO }

type IOrgDo interface {
	gen.SubQuery
	Debug() IOrgDo
	WithContext(ctx context.Context) IOrgDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IOrgDo
	WriteDB() IOrgDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IOrgDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IOrgDo
	Not(conds ...gen.Condition) IOrgDo
	Or(conds ...gen.Condition) IOrgDo
	Select(conds ...field.Expr) IOrgDo
	Where(conds ...gen.Condition) IOrgDo
	Order(conds ...field.Expr) IOrgDo
	Distinct(cols ...field.Expr) IOrgDo
	Omit(cols ...field.Expr) IOrgDo
	Join(table schema.Tabler, on ...field.Expr) IOrgDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IOrgDo
	RightJoin(table schema.Tabler, on ...field.Expr) IOrgDo
	Group(cols ...field.Expr) IOrgDo
	Having(conds ...gen.Condition) IOrgDo
	Limit(limit int) IOrgDo
	Offset(offset int) IOrgDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IOrgDo
	Unscoped() IOrgDo
	Create(values ...*model.Org) error
	CreateInBatches(values []*model.Org, batchSize int) error
	Save(values ...*model.Org) error
	First() (*model.Org, error)
	Take() (*model.Org, error)
	Last() (*model.Org, error)
	Find() ([]*model.Org, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Org, err error)
	FindInBatches(result *[]*model.Org, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Org) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IOrgDo
	Assign(attrs ...field.AssignExpr) IOrgDo
	Joins(fields ...field.RelationField) IOrgDo
	Preload(fields ...field.RelationField) IOrgDo
	FirstOrInit() (*model.Org, error)
	FirstOrCreate() (*model.Org, error)
	FindByPage(offset int, limit int) (result []*model.Org, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IOrgDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (o orgDo) Debug() IOrgDo {
	return o.withDO(o.DO.Debug())
}

func (o orgDo) WithContext(ctx context.Context) IOrgDo {
	return o.withDO(o.DO.WithContext(ctx))
}

func (o orgDo) ReadDB() IOrgDo {
	return o.Clauses(dbresolver.Read)
}

func (o orgDo) WriteDB() IOrgDo {
	return o.Clauses(dbresolver.Write)
}

func (o orgDo) Session(config *gorm.Session) IOrgDo {
	return o.withDO(o.DO.Session(config))
}

func (o orgDo) Clauses(conds ...clause.Expression) IOrgDo {
	return o.withDO(o.DO.Clauses(conds...))
}

func (o orgDo) Returning(value interface{}, columns ...string) IOrgDo {
	return o.withDO(o.DO.Returning(value, columns...))
}

func (o orgDo) Not(conds ...gen.Condition) IOrgDo {
	return o.withDO(o.DO.Not(conds...))
}

func (o orgDo) Or(conds ...gen.Condition) IOrgDo {
	return o.withDO(o.DO.Or(conds...))
}

func (o orgDo) Select(conds ...field.Expr) IOrgDo {
	return o.withDO(o.DO.Select(conds...))
}

func (o orgDo) Where(conds ...gen.Condition) IOrgDo {
	return o.withDO(o.DO.Where(conds...))
}

func (o orgDo) Order(conds ...field.Expr) IOrgDo {
	return o.withDO(o.DO.Order(conds...))
}

func (o orgDo) Distinct(cols ...field.Expr) IOrgDo {
	return o.withDO(o.DO.Distinct(cols...))
}

func (o orgDo) Omit(cols ...field.Expr) IOrgDo {
	return o.withDO(o.DO.Omit(cols...))
}

func (o orgDo) Join(table schema.Tabler, on ...field.Expr) IOrgDo {
	return o.withDO(o.DO.Join(table, on...))
}

func (o orgDo) LeftJoin(table schema.Tabler, on ...field.Expr) IOrgDo {
	return o.withDO(o.DO.LeftJoin(table, on...))
}

func (o orgDo) RightJoin(table schema.Tabler, on ...field.Expr) IOrgDo {
	return o.withDO(o.DO.RightJoin(table, on...))
}

func (o orgDo) Group(cols ...field.Expr) IOrgDo {
	return o.withDO(o.DO.Group(cols...))
}

func (o orgDo) Having(conds ...gen.Condition) IOrgDo {
	return o.withDO(o.DO.Having(conds...))
}

func (o orgDo) Limit(limit int) IOrgDo {
	return o.withDO(o.DO.Limit(limit))
}

func (o orgDo) Offset(offset int) IOrgDo {
	return o.withDO(o.DO.Offset(offset))
}

func (o orgDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IOrgDo {
	return o.withDO(o.DO.Scopes(funcs...))
}

func (o orgDo) Unscoped() IOrgDo {
	return o.withDO(o.DO.Unscoped())
}

func (o orgDo) Create(values ...*model.Org) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Create(values)
}

func (o orgDo) CreateInBatches(values []*model.Org, batchSize int) error {
	return o.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (o orgDo) Save(values ...*model.Org) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Save(values)
}

func (o orgDo) First() (*model.Org, error) {
	if result, err := o.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Org), nil
	}
}

func (o orgDo) Take() (*model.Org, error) {
	if result, err := o.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Org), nil
	}
}

func (o orgDo) Last() (*model.Org, error) {
	if result, err := o.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Org), nil
	}
}

func (o orgDo) Find() ([]*model.Org, error) {
	result, err := o.DO.Find()
	return result.([]*model.Org), err
}

func (o orgDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Org, err error) {
	buf := make([]*model.Org, 0, batchSize)
	err = o.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (o orgDo) FindInBatches(result *[]*model.Org, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return o.DO.FindInBatches(result, batchSize, fc)
}

func (o orgDo) Attrs(attrs ...field.AssignExpr) IOrgDo {
	return o.withDO(o.DO.Attrs(attrs...))
}

func (o orgDo) Assign(attrs ...field.AssignExpr) IOrgDo {
	return o.withDO(o.DO.Assign(attrs...))
}

func (o orgDo) Joins(fields ...field.RelationField) IOrgDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Joins(_f))
	}
	return &o
}

func (o orgDo) Preload(fields ...field.RelationField) IOrgDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Preload(_f))
	}
	return &o
}

func (o orgDo) FirstOrInit() (*model.Org, error) {
	if result, err := o.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Org), nil
	}
}

func (o orgDo) FirstOrCreate() (*model.Org, error) {
	if result, err := o.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Org), nil
	}
}

func (o orgDo) FindByPage(offset int, limit int) (result []*model.Org, count int64, err error) {
	result, err = o.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = o.Offset(-1).Limit(-1).Count()
	return
}

func (o orgDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = o.Count()
	if err != nil {
		return
	}

	err = o.Offset(offset).Limit(limit).Scan(result)
	return
}

func (o orgDo) Scan(result interface{}) (err error) {
	return o.DO.Scan(result)
}

func (o orgDo) Delete(models ...*model.Org) (result gen.ResultInfo, err error) {
	return o.DO.Delete(models)
}

func (o *orgDo) withDO(do gen.Dao) *orgDo {
	o.DO = *do.(*gen.DO)
	return o
}
