// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"project/internal/model"
)

func newWarrantyApplication(db *gorm.DB, opts ...gen.DOOption) warrantyApplication {
	_warrantyApplication := warrantyApplication{}

	_warrantyApplication.warrantyApplicationDo.UseDB(db, opts...)
	_warrantyApplication.warrantyApplicationDo.UseModel(&model.WarrantyApplication{})

	tableName := _warrantyApplication.warrantyApplicationDo.TableName()
	_warrantyApplication.ALL = field.NewAsterisk(tableName)
	_warrantyApplication.ID = field.NewString(tableName, "id")
	_warrantyApplication.DeviceID = field.NewString(tableName, "device_id")
	_warrantyApplication.UserID = field.NewString(tableName, "user_id")
	_warrantyApplication.Type = field.NewString(tableName, "type")
	_warrantyApplication.Description = field.NewString(tableName, "description")
	_warrantyApplication.Image = field.NewString(tableName, "images")
	_warrantyApplication.Status = field.NewString(tableName, "status")
	_warrantyApplication.ResultInfo = field.NewString(tableName, "result_info")
	_warrantyApplication.HandlerID = field.NewString(tableName, "handler_id")
	_warrantyApplication.TenantID = field.NewString(tableName, "tenant_id")
	_warrantyApplication.CreatedAt = field.NewTime(tableName, "created_at")
	_warrantyApplication.UpdatedAt = field.NewTime(tableName, "updated_at")

	_warrantyApplication.fillFieldMap()

	return _warrantyApplication
}

type warrantyApplication struct {
	warrantyApplicationDo

	ALL         field.Asterisk
	ID          field.String
	DeviceID    field.String
	UserID      field.String
	Type        field.String
	Description field.String
	Image       field.String
	Status      field.String
	ResultInfo  field.String
	HandlerID   field.String
	TenantID    field.String
	CreatedAt   field.Time
	UpdatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (w warrantyApplication) Table(newTableName string) *warrantyApplication {
	w.warrantyApplicationDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w warrantyApplication) As(alias string) *warrantyApplication {
	w.warrantyApplicationDo.DO = *(w.warrantyApplicationDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *warrantyApplication) updateTableName(table string) *warrantyApplication {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewString(table, "id")
	w.DeviceID = field.NewString(table, "device_id")
	w.UserID = field.NewString(table, "user_id")
	w.Type = field.NewString(table, "type")
	w.Description = field.NewString(table, "description")
	w.Image = field.NewString(table, "images")
	w.Status = field.NewString(table, "status")
	w.ResultInfo = field.NewString(table, "result_info")
	w.HandlerID = field.NewString(table, "handler_id")
	w.TenantID = field.NewString(table, "tenant_id")
	w.CreatedAt = field.NewTime(table, "created_at")
	w.UpdatedAt = field.NewTime(table, "updated_at")

	w.fillFieldMap()

	return w
}

func (w *warrantyApplication) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *warrantyApplication) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 12)
	w.fieldMap["id"] = w.ID
	w.fieldMap["device_id"] = w.DeviceID
	w.fieldMap["user_id"] = w.UserID
	w.fieldMap["type"] = w.Type
	w.fieldMap["description"] = w.Description
	w.fieldMap["images"] = w.Image
	w.fieldMap["status"] = w.Status
	w.fieldMap["result_info"] = w.ResultInfo
	w.fieldMap["handler_id"] = w.HandlerID
	w.fieldMap["tenant_id"] = w.TenantID
	w.fieldMap["created_at"] = w.CreatedAt
	w.fieldMap["updated_at"] = w.UpdatedAt
}

func (w warrantyApplication) clone(db *gorm.DB) warrantyApplication {
	w.warrantyApplicationDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w warrantyApplication) replaceDB(db *gorm.DB) warrantyApplication {
	w.warrantyApplicationDo.ReplaceDB(db)
	return w
}

type warrantyApplicationDo struct{ gen.DO }

type IWarrantyApplicationDo interface {
	gen.SubQuery
	Debug() IWarrantyApplicationDo
	WithContext(ctx context.Context) IWarrantyApplicationDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IWarrantyApplicationDo
	WriteDB() IWarrantyApplicationDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IWarrantyApplicationDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IWarrantyApplicationDo
	Not(conds ...gen.Condition) IWarrantyApplicationDo
	Or(conds ...gen.Condition) IWarrantyApplicationDo
	Select(conds ...field.Expr) IWarrantyApplicationDo
	Where(conds ...gen.Condition) IWarrantyApplicationDo
	Order(conds ...field.Expr) IWarrantyApplicationDo
	Distinct(cols ...field.Expr) IWarrantyApplicationDo
	Omit(cols ...field.Expr) IWarrantyApplicationDo
	Join(table schema.Tabler, on ...field.Expr) IWarrantyApplicationDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IWarrantyApplicationDo
	RightJoin(table schema.Tabler, on ...field.Expr) IWarrantyApplicationDo
	Group(cols ...field.Expr) IWarrantyApplicationDo
	Having(conds ...gen.Condition) IWarrantyApplicationDo
	Limit(limit int) IWarrantyApplicationDo
	Offset(offset int) IWarrantyApplicationDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IWarrantyApplicationDo
	Unscoped() IWarrantyApplicationDo
	Create(values ...*model.WarrantyApplication) error
	CreateInBatches(values []*model.WarrantyApplication, batchSize int) error
	Save(values ...*model.WarrantyApplication) error
	First() (*model.WarrantyApplication, error)
	Take() (*model.WarrantyApplication, error)
	Last() (*model.WarrantyApplication, error)
	Find() ([]*model.WarrantyApplication, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WarrantyApplication, err error)
	FindInBatches(result *[]*model.WarrantyApplication, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.WarrantyApplication) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IWarrantyApplicationDo
	Assign(attrs ...field.AssignExpr) IWarrantyApplicationDo
	Joins(fields ...field.RelationField) IWarrantyApplicationDo
	Preload(fields ...field.RelationField) IWarrantyApplicationDo
	FirstOrInit() (*model.WarrantyApplication, error)
	FirstOrCreate() (*model.WarrantyApplication, error)
	FindByPage(offset int, limit int) (result []*model.WarrantyApplication, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IWarrantyApplicationDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (w warrantyApplicationDo) Debug() IWarrantyApplicationDo {
	return w.withDO(w.DO.Debug())
}

func (w warrantyApplicationDo) WithContext(ctx context.Context) IWarrantyApplicationDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w warrantyApplicationDo) ReadDB() IWarrantyApplicationDo {
	return w.Clauses(dbresolver.Read)
}

func (w warrantyApplicationDo) WriteDB() IWarrantyApplicationDo {
	return w.Clauses(dbresolver.Write)
}

func (w warrantyApplicationDo) Session(config *gorm.Session) IWarrantyApplicationDo {
	return w.withDO(w.DO.Session(config))
}

func (w warrantyApplicationDo) Clauses(conds ...clause.Expression) IWarrantyApplicationDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w warrantyApplicationDo) Returning(value interface{}, columns ...string) IWarrantyApplicationDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w warrantyApplicationDo) Not(conds ...gen.Condition) IWarrantyApplicationDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w warrantyApplicationDo) Or(conds ...gen.Condition) IWarrantyApplicationDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w warrantyApplicationDo) Select(conds ...field.Expr) IWarrantyApplicationDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w warrantyApplicationDo) Where(conds ...gen.Condition) IWarrantyApplicationDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w warrantyApplicationDo) Order(conds ...field.Expr) IWarrantyApplicationDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w warrantyApplicationDo) Distinct(cols ...field.Expr) IWarrantyApplicationDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w warrantyApplicationDo) Omit(cols ...field.Expr) IWarrantyApplicationDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w warrantyApplicationDo) Join(table schema.Tabler, on ...field.Expr) IWarrantyApplicationDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w warrantyApplicationDo) LeftJoin(table schema.Tabler, on ...field.Expr) IWarrantyApplicationDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w warrantyApplicationDo) RightJoin(table schema.Tabler, on ...field.Expr) IWarrantyApplicationDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w warrantyApplicationDo) Group(cols ...field.Expr) IWarrantyApplicationDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w warrantyApplicationDo) Having(conds ...gen.Condition) IWarrantyApplicationDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w warrantyApplicationDo) Limit(limit int) IWarrantyApplicationDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w warrantyApplicationDo) Offset(offset int) IWarrantyApplicationDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w warrantyApplicationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IWarrantyApplicationDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w warrantyApplicationDo) Unscoped() IWarrantyApplicationDo {
	return w.withDO(w.DO.Unscoped())
}

func (w warrantyApplicationDo) Create(values ...*model.WarrantyApplication) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w warrantyApplicationDo) CreateInBatches(values []*model.WarrantyApplication, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w warrantyApplicationDo) Save(values ...*model.WarrantyApplication) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w warrantyApplicationDo) First() (*model.WarrantyApplication, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.WarrantyApplication), nil
	}
}

func (w warrantyApplicationDo) Take() (*model.WarrantyApplication, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.WarrantyApplication), nil
	}
}

func (w warrantyApplicationDo) Last() (*model.WarrantyApplication, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.WarrantyApplication), nil
	}
}

func (w warrantyApplicationDo) Find() ([]*model.WarrantyApplication, error) {
	result, err := w.DO.Find()
	return result.([]*model.WarrantyApplication), err
}

func (w warrantyApplicationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WarrantyApplication, err error) {
	buf := make([]*model.WarrantyApplication, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w warrantyApplicationDo) FindInBatches(result *[]*model.WarrantyApplication, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w warrantyApplicationDo) Attrs(attrs ...field.AssignExpr) IWarrantyApplicationDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w warrantyApplicationDo) Assign(attrs ...field.AssignExpr) IWarrantyApplicationDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w warrantyApplicationDo) Joins(fields ...field.RelationField) IWarrantyApplicationDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w warrantyApplicationDo) Preload(fields ...field.RelationField) IWarrantyApplicationDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w warrantyApplicationDo) FirstOrInit() (*model.WarrantyApplication, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.WarrantyApplication), nil
	}
}

func (w warrantyApplicationDo) FirstOrCreate() (*model.WarrantyApplication, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.WarrantyApplication), nil
	}
}

func (w warrantyApplicationDo) FindByPage(offset int, limit int) (result []*model.WarrantyApplication, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w warrantyApplicationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w warrantyApplicationDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w warrantyApplicationDo) Delete(models ...*model.WarrantyApplication) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *warrantyApplicationDo) withDO(do gen.Dao) *warrantyApplicationDo {
	w.DO = *do.(*gen.DO)
	return w
}
