package service

import "project/internal/model"

func leafNode(label, value, registerAddress string, paramKeys ...string) model.DeviceParamTreeNode {
	return model.DeviceParamTreeNode{
		Label:           label,
		Value:           value,
		RegisterAddress: registerAddress,
		ParamKeys:       paramKeys,
	}
}

func buildDeviceParamPermissionTree() []model.DeviceParamTreeNode {
	return []model.DeviceParamTreeNode{
		{
			Label: "单体设置",
			Value: "group:single",
			Children: []model.DeviceParamTreeNode{
				leafNode("单体过压告警电压", "400", "0x0400", "CELL_OV_ALARM_V"),
				leafNode("单体过充保护电压", "401", "0x0401", "CELL_OC_PROTECT_V"),
				leafNode("单体过充告警延时 / 单体过充保护延时", "402", "0x0402", "CELL_OC_ALARM_DELAY_S", "CELL_OC_PROTECT_DELAY_S"),
				leafNode("回馈过充保护延时 / 常温低温阀值温度", "403", "0x0403", "FEEDBACK_OC_PROTECT_DELAY_S", "NORMAL_LOW_TEMP_THRESHOLD_C"),
				leafNode("单体过充告警解除电压差", "404", "0x0404", "CELL_OC_ALARM_RELEASE_DELTA_V"),
				leafNode("单体过充保护解除电压", "405", "0x0405", "CELL_OV_PROTECT_RELEASE_V"),
				leafNode("单体过压告警解除延时 / 单体过压保护解除延时", "408", "0x0408", "CELL_OV_ALARM_RELEASE_DELAY_S", "CELL_OV_PROTECT_RELEASE_DELAY_S"),
				leafNode("常温单体过放告警电压", "409", "0x0409", "NORMAL_CELL_UV_ALARM_V"),
				leafNode("常温单体过放保护电压", "40a", "0x040A", "NORMAL_CELL_UV_PROTECT_V"),
				leafNode("单体过放告警延时 / 单体过放保护延时", "40d", "0x040D", "CELL_UV_ALARM_DELAY_S", "CELL_UV_PROTECT_DELAY_S"),
				leafNode("单体过放告警解除电压", "40e", "0x040E", "CELL_UV_ALARM_RELEASE_V"),
				leafNode("单体过放保护解除电压", "40f", "0x040F", "CELL_UV_PROTECT_RELEASE_V"),
				leafNode("单体过放告警解除延时 / 单体过放保护解除延时", "410", "0x0410", "CELL_UV_ALARM_RELEASE_DELAY_S", "CELL_UV_PROTECT_RELEASE_DELAY_S"),
			},
		},
		{
			Label: "总压设置",
			Value: "group:voltage",
			Children: []model.DeviceParamTreeNode{
				leafNode("总压过压告警电压", "411", "0x0411", "PACK_OV_ALARM_V"),
				leafNode("总压过压保护电压", "412", "0x0412", "PACK_OV_PROTECT_V"),
				leafNode("总压过压保护延时 / 总压过压告警延时", "413", "0x0413", "PACK_OV_PROTECT_DELAY_S", "PACK_OV_ALARM_DELAY_S"),
				leafNode("总压过压告警解除电压", "414", "0x0414", "PACK_OV_ALARM_RELEASE_V"),
				leafNode("总压过压保护解除电压", "415", "0x0415", "PACK_OV_PROTECT_RELEASE_V"),
				leafNode("总压过放告警延时 / 总压过放保护延时", "41b", "0x041B", "PACK_UV_ALARM_DELAY_S", "PACK_UV_PROTECT_DELAY_S"),
				leafNode("总压过压解除延时 / 总压过压告警解除延时", "416", "0x0416", "PACK_OV_PROTECT_RELEASE_DELAY_S", "PACK_OV_ALARM_RELEASE_DELAY_S"),
				leafNode("常温总压欠压告警电压", "417", "0x0417", "NORMAL_PACK_UV_ALARM_V"),
				leafNode("常温总压欠压保护电压", "418", "0x0418", "NORMAL_PACK_UV_PROTECT_V"),
				leafNode("低温总压欠压告警电压", "419", "0x0419", "LOW_TEMP_PACK_UV_ALARM_V"),
				leafNode("低温总压欠压保护电压", "41a", "0x041A", "LOW_TEMP_PACK_UV_PROTECT_V"),
				leafNode("总压欠压告警解除电压", "41c", "0x041C", "PACK_UV_ALARM_RELEASE_V"),
				leafNode("总压欠压保护解除电压", "41d", "0x041D", "PACK_UV_PROTECT_RELEASE_V"),
				leafNode("总压过放告警解除延时 / 总压过放保护解除延时", "41e", "0x041E", "PACK_UV_ALARM_RELEASE_DELAY_S", "PACK_UV_PROTECT_RELEASE_DELAY_S"),
			},
		},
		{
			Label: "电流设置",
			Value: "group:current",
			Children: []model.DeviceParamTreeNode{
				leafNode("充电过流告警电流", "41f", "0x041F", "CHARGE_OC_ALARM_A"),
				leafNode("充电过流保护小电流", "420", "0x0420", "CHARGE_OC_PROTECT_SMALL_A"),
				leafNode("充电过流保护大电流", "421", "0x0421", "CHARGE_OC_PROTECT_LARGE_A"),
				leafNode("充电过流告警延时 / 充电过流保护大电流延时", "422", "0x0422", "CHARGE_OC_ALARM_DELAY_S", "CHARGE_OC_PROTECT_LARGE_DELAY_S"),
				leafNode("充电过流保护小电流延时", "423", "0x0423", "CHARGE_OC_PROTECT_SMALL_DELAY_S"),
				leafNode("放电过流告警电流", "427", "0x0427", "DISCHARGE_OC_ALARM_A"),
				leafNode("放电过流小电流保护电流", "428", "0x0428", "DISCHARGE_OC_PROTECT_SMALL_A"),
				leafNode("放电过流大电流保护电流", "429", "0x0429", "DISCHARGE_OC_PROTECT_LARGE_A"),
				leafNode("放电过流告警延时 / 放电过流大电流保护延时", "42a", "0x042A", "DISCHARGE_OC_ALARM_DELAY_S", "DISCHARGE_OC_PROTECT_LARGE_DELAY_S"),
				leafNode("放电过流小电流保护延时", "42b", "0x042B", "DISCHARGE_OC_PROTECT_SMALL_DELAY_S"),
			},
		},
		{
			Label: "温度设置",
			Value: "group:temperature",
			Children: []model.DeviceParamTreeNode{
				leafNode("MOS高温保护温度", "438", "0x0438(H)", "MOS_OT_PROTECT_C"),
				leafNode("MOS高温保护解除温度", "439", "0x0439(H)", "MOS_OT_PROTECT_RELEASE_C"),
				leafNode("MOS高温保护延时", "43a", "0x043A", "MOS_OT_PROTECT_DELAY_S"),
				leafNode("MOS高温保护解除延时", "43b", "0x043B", "MOS_OT_PROTECT_RELEASE_DELAY_S"),
				leafNode("充电低温保护温度", "442", "0x0442(H)", "CHARGE_UT_PROTECT_C"),
				leafNode("充电低温保护解除温度", "443", "0x0443(H)", "CHARGE_UT_PROTECT_RELEASE_C"),
				leafNode("充电高温保护温度", "444", "0x0444(H)", "CHARGE_OT_PROTECT_C"),
				leafNode("充电高温保护解除温度", "445", "0x0445(H)", "CHARGE_OT_PROTECT_RELEASE_C"),
				leafNode("充电高低温告警延时 / 充电高低温保护延时", "446", "0x0446", "CHARGE_OT_ALARM_DELAY_S", "CHARGE_OT_PROTECT_DELAY_S"),
				leafNode("充电高低温告警解除延时 / 充电高低温保护解除延时", "447", "0x0447", "CHARGE_OT_ALARM_RELEASE_DELAY_S", "CHARGE_OT_PROTECT_RELEASE_DELAY_S"),
				leafNode("放电低温保护温度", "448", "0x0448(H)", "DISCHARGE_UT_PROTECT_C"),
				leafNode("放电低温保护解除温度", "449", "0x0449(H)", "DISCHARGE_UT_PROTECT_RELEASE_C"),
				leafNode("放电高温保护温度", "44a", "0x044A(H)", "DISCHARGE_OT_PROTECT_C"),
				leafNode("放电高温保护解除温度", "44b", "0x044B", "DISCHARGE_OT_PROTECT_RELEASE_C"),
				leafNode("放电高低温告警延时 / 放电高低温保护延时", "44c", "0x044C", "DISCHARGE_OT_ALARM_DELAY_S", "DISCHARGE_OT_PROTECT_DELAY_S"),
				leafNode("放电高低温告警解除延时 / 放电高低温保护解除延时", "44d", "0x044D", "DISCHARGE_OT_ALARM_RELEASE_DELAY_S", "DISCHARGE_OT_PROTECT_RELEASE_DELAY_S"),
				leafNode("电芯高温告警 / 电芯高温告警解除", "44e", "0x044E", "CELL_OT_ALARM_C", "CELL_OT_ALARM_RELEASE_C"),
				leafNode("高温告警延时 / 高温告警解除延时", "44f", "0x044F", "CELL_OT_ALARM_DELAY_S", "CELL_OT_ALARM_RELEASE_DELAY_S"),
				leafNode("加热电芯开启温度 / 加热电芯关闭温度", "450", "0x0450", "HEAT_CELL_ON_C", "HEAT_CELL_OFF_C"),
				leafNode("加热膜温度保护 / 加热膜温度保护恢复", "451", "0x0451", "HEAT_FILM_PROTECT_C", "HEAT_FILM_PROTECT_RELEASE_C"),
				leafNode("开启延时 / 关闭延时", "452", "0x0452", "HEAT_ON_DELAY_S", "HEAT_OFF_DELAY_S"),
				leafNode("极柱温度保护 / 极柱温度保护恢复", "453", "0x0453", "POLE_TEMP_PROTECT_C", "POLE_TEMP_PROTECT_RELEASE_C"),
			},
		},
		{
			Label: "高级参数",
			Value: "group:advanced",
			Children: []model.DeviceParamTreeNode{
				{
					Label: "高级配置",
					Value: "group:advanced:other",
					Children: []model.DeviceParamTreeNode{
						leafNode("只读 SOH", "10d", "0x010D", "SOH_PCT"),
						leafNode("均衡开启电压", "454", "0x0454", "BALANCE_START_V"),
						leafNode("开启压差 / 停止压差", "455", "0x0455", "BALANCE_START_DELTA_V", "BALANCE_STOP_DELTA_V"),
						leafNode("高温禁止 / 低温禁止", "456", "0x0456", "BALANCE_DISABLE_HIGH_TEMP_C", "BALANCE_DISABLE_LOW_TEMP_C"),
						leafNode("压差报警压差 / 压差报警恢复压差", "457", "0x0457", "DELTA_V_ALARM_THRESHOLD_V", "DELTA_V_ALARM_RELEASE_V"),
						leafNode("压差保护压差 / 压差保护恢复压差", "458", "0x0458", "DELTA_V_PROTECT_THRESHOLD_V", "DELTA_V_PROTECT_RELEASE_V"),
						leafNode("压差保护延时 / 压差解除延时", "459", "0x0459", "DELTA_V_PROTECT_DELAY_S", "DELTA_V_RELEASE_DELAY_S"),
						leafNode("温差报警 / 温差报警恢复", "45a", "0x045A", "TEMP_DIFF_ALARM_THRESHOLD_C", "TEMP_DIFF_ALARM_RELEASE_C"),
						leafNode("温差保护 / 温差保护恢复", "45b", "0x045B", "TEMP_DIFF_PROTECT_THRESHOLD_C", "TEMP_DIFF_PROTECT_RELEASE_C"),
						leafNode("温差保护延时 / 温差解除延时", "45c", "0x045C", "TEMP_DIFF_PROTECT_DELAY_S", "TEMP_DIFF_RELEASE_DELAY_S"),
						leafNode("电量低告警门槛", "45d", "0x045D(L)", "LOW_SOC_ALARM_THRESHOLD_PCT"),
						leafNode(">=总压", "45e", "0x045E", "FULL_CHARGE_PACK_V"),
						leafNode("小于电流", "45f", "0x045F", "FULL_CHARGE_CURRENT_A"),
						leafNode("持续时间", "460", "0x0460(L)", "FULL_CHARGE_DURATION_S"),
						leafNode("虚拟容量写入", "627", "0x0627", "VIRTUAL_CAPACITY_AH"),
					},
				},
				{
					Label: "编号配置",
					Value: "group:advanced:numbering",
					Children: []model.DeviceParamTreeNode{
						leafNode("电池组编号", "500", "0x0500", "BATTERY_GROUP_ID"),
						leafNode("DTU域名和端口地址", "53a", "0x053A", "DTU_DOMAIN_PORT"),
					},
				},
				{
					Label: "系统配置",
					Value: "group:advanced:system",
					Children: []model.DeviceParamTreeNode{
						leafNode("高低串数配置", "1", "0x0001", "SERIES_COUNT_CONFIG"),
						leafNode("电池类型", "4", "0x0004", "BATTERY_TYPE"),
						leafNode("设计容量", "30", "0x0030", "DESIGN_CAPACITY_AH"),
						leafNode("满充容量", "32", "0x0032", "FULL_CAPACITY_AH"),
						leafNode("剩余容量", "34", "0x0034", "REMAIN_CAPACITY_AH"),
						{
							Label: "功能控制",
							Value: "group:advanced:system:function",
							Children: []model.DeviceParamTreeNode{
								leafNode("保温加热功能", "function:insulationHeatingEnabled", "0x003E", "FUNCTION_CONFIG", "insulationHeatingEnabled"),
								leafNode("放电加热功能", "function:dischargeHeatingEnabled", "0x003E", "FUNCTION_CONFIG", "dischargeHeatingEnabled"),
								leafNode("低温加热功能", "function:lowTempHeatingEnabled", "0x003E", "FUNCTION_CONFIG", "lowTempHeatingEnabled"),
								leafNode("充电允许", "function:chargeAllowed", "0x003E", "FUNCTION_CONFIG", "chargeAllowed"),
								leafNode("放电允许", "function:dischargeAllowed", "0x003E", "FUNCTION_CONFIG", "dischargeAllowed"),
							},
						},
					},
				},
				{
					Label: "出厂配置",
					Value: "group:advanced:factory",
					Children: []model.DeviceParamTreeNode{
						leafNode("进入测试模式", "factory:enterTestMode", "0x057A~0x057B", "enterTestMode"),
						leafNode("退出测试模式", "factory:exitTestMode", "0x057A~0x057B", "exitTestMode"),
						leafNode("开启全均衡", "factory:balanceAllOn", "0x057A~0x057B", "balanceAllOn"),
						leafNode("关闭全均衡", "factory:balanceAllOff", "0x057A~0x057B", "balanceAllOff"),
						leafNode("功能1打开", "factory:function1On", "0x057A~0x057B(BIT22)", "function1On"),
						leafNode("功能1关闭", "factory:function1Off", "0x057A~0x057B(BIT22)", "function1Off"),
						leafNode("功能2打开", "factory:function2On", "0x057A~0x057B(BIT24)", "function2On"),
						leafNode("功能2关闭", "factory:function2Off", "0x057A~0x057B(BIT24)", "function2Off"),
						leafNode("功能3打开", "factory:function3On", "0x057A~0x057B(BIT26)", "function3On"),
						leafNode("功能3关闭", "factory:function3Off", "0x057A~0x057B(BIT26)", "function3Off"),
						leafNode("功能4打开", "factory:function4On", "0x057A~0x057B(BIT28)", "function4On"),
						leafNode("功能4关闭", "factory:function4Off", "0x057A~0x057B(BIT28)", "function4Off"),
						leafNode("擦除当前参数", "factory:eraseCurrentParams", "0x057A~0x057B(BIT16)", "eraseCurrentParams"),
						leafNode("擦除历史记录", "factory:eraseHistoryRecords", "0x057A~0x057B(BIT17)", "eraseHistoryRecords"),
						leafNode("擦除循环次数", "factory:eraseCycleCount", "0x057A~0x057B(BIT18)", "eraseCycleCount"),
						leafNode("清除保护状态", "factory:clearProtectionStatus", "0x057A~0x057B(BIT19)", "clearProtectionStatus"),
						leafNode("复位保护板", "factory:resetProtectionBoard", "0x057A~0x057B(BIT21)", "resetProtectionBoard"),
						leafNode("MCU进入保护", "factory:mcuProtectionOn", "0x057A~0x057B(BIT14)", "mcuProtectionOn"),
						leafNode("MCU退出保护", "factory:mcuProtectionOff", "0x057A~0x057B(BIT14)", "mcuProtectionOff"),
						leafNode("手动打开充放电管", "factory:manualChargeDischargeOn", "0x057A~0x057B(BIT8)", "manualChargeDischargeOn"),
						leafNode("手动关闭充放电管", "factory:manualChargeDischargeOff", "0x057A~0x057B(BIT8)", "manualChargeDischargeOff"),
						leafNode("手动打开加热", "factory:manualHeatingOn", "0x057A~0x057B(BIT6)", "manualHeatingOn"),
						leafNode("手动关闭加热", "factory:manualHeatingOff", "0x057A~0x057B(BIT6)", "manualHeatingOff"),
						leafNode("GPS电源打开", "factory:gpsPowerOn", "0x057A~0x057B(BIT4)", "gpsPowerOn"),
						leafNode("GPS电源关闭", "factory:gpsPowerOff", "0x057A~0x057B(BIT4)", "gpsPowerOff"),
						leafNode("进入休眠", "factory:sleep", "0x057A~0x057B", "sleep"),
						leafNode("关机", "factory:powerOff", "0x057A~0x057B", "powerOff"),
					},
				},
			},
		},
	}
}
